In [1]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.13/dist-packages (4.0.4)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.13/dist-packages (from pyspark) (0.10.9.9)

In [2]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Advanced Pyspark").getOrCreate()

In [3]:
from google.colab import files

uploaded = files.upload()

Saving machine_configurations.json to machine_configurations.json
Saving plant_master.csv to plant_master.csv
Saving manufacturing_production_extra_12k.csv to manufacturing_production_extra_12k.csv
Saving manufacturing_production_120k.csv to manufacturing_production_120k.csv
Saving machine_master.csv to machine_master.csv

**1. Load the Data in PySpark**

In [4]:
df = spark.read.csv(
"manufacturing_production_120k.csv",
    header=True,
    inferSchema=True
)

1. Display first 20 rows.

In [ ]:
df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

2. Display schema.

In [ ]:
df.printSchema()

root
 |-- production_id: string (nullable = true)
 |-- production_date: date (nullable = true)
 |-- plant_id: string (nullable = true)
 |-- machine_id: string (nullable = true)
 |-- operator_id: string (nullable = true)
 |-- shift: string (nullable = true)
 |-- product_code: string (nullable = true)
 |-- product_family: string (nullable = true)
 |-- units_planned: integer (nullable = true)
 |-- units_produced: integer (nullable = true)
 |-- defective_units: integer (nullable = true)
 |-- downtime_minutes: integer (nullable = true)
 |-- energy_kwh: double (nullable = true)
 |-- temperature_c: double (nullable = true)
 |-- vibration_mm_s: double (nullable = true)
 |-- quality_status: string (nullable = true)
 |-- maintenance_flag: string (nullable = true)
 |-- supervisor: string (nullable = true)

3. Display column names.

In [ ]:
print(df.columns)

['production_id', 'production_date', 'plant_id', 'machine_id', 'operator_id', 'shift', 'product_code', 'product_family', 'units_planned', 'units_produced', 'defective_units', 'downtime_minutes', 'energy_kwh', 'temperature_c', 'vibration_mm_s', 'quality_status', 'maintenance_flag', 'supervisor']

4. Count total records.

In [ ]:
print(df.count())

120000

5. Display only production ID, plant, machine, product family and units produced.

In [ ]:
df.select("production_id", "plant_id", "machine_id", "product_family", "units_produced").show()

+-------------+--------+----------+--------------+--------------+
|production_id|plant_id|machine_id|product_family|units_produced|
+-------------+--------+----------+--------------+--------------+
|    PR0000001|    PL03|     MC011|        Motors|           993|
|    PR0000002|    PL04|     MC019|   Controllers|           836|
|    PR0000003|    PL01|     MC002|        Motors|           380|
|    PR0000004|    PL03|     MC013|         Pumps|           720|
|    PR0000005|    PL04|     MC020|         Pumps|           296|
|    PR0000006|    PL01|     MC002|        Motors|           795|
|    PR0000007|    PL02|     MC007|        Valves|           955|
|    PR0000008|    PL02|     MC009|        Valves|           895|
|    PR0000009|    PL03|     MC015|   Controllers|           289|
|    PR0000010|    PL02|     MC006|   Controllers|           527|
|    PR0000011|    PL03|     MC012|         Pumps|           512|
|    PR0000012|    PL06|     MC030|   Controllers|           968|
|    PR0000013|    PL06|     MC027|   Controllers|           867|
|    PR0000014|    PL03|     MC013|        Valves|           456|
|    PR0000015|    PL02|     MC007|        Motors|          1042|
|    PR0000016|    PL04|     MC020|   Controllers|           732|
|    PR0000017|    PL03|     MC011|   Controllers|           963|
|    PR0000018|    PL03|     MC012|        Motors|           469|
|    PR0000019|    PL01|     MC005|        Valves|           380|
|    PR0000020|    PL03|     MC014|         Pumps|           573|
+-------------+--------+----------+--------------+--------------+
only showing top 20 rows

6. Check the datatype of each column.

In [ ]:
print(df.dtypes)

[('production_id', 'string'), ('production_date', 'date'), ('plant_id', 'string'), ('machine_id', 'string'), ('operator_id', 'string'), ('shift', 'string'), ('product_code', 'string'), ('product_family', 'string'), ('units_planned', 'int'), ('units_produced', 'int'), ('defective_units', 'int'), ('downtime_minutes', 'int'), ('energy_kwh', 'double'), ('temperature_c', 'double'), ('vibration_mm_s', 'double'), ('quality_status', 'string'), ('maintenance_flag', 'string'), ('supervisor', 'string')]

7. Display 10 random-looking sample records using sample().

In [5]:
df.sample(withReplacement=False, fraction=0.1, seed=42).show(10)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000051|     2026-06-12|    PL05|     MC021|     OP0337|Morning|     PMP-310|         Pumps|          960|           975|             17|              51|    380.84|        72.08|          3.59|          Pass|              No|    Bharat|
|    PR0000059|     2026-09-27|    PL04|     MC018|     OP0276|Morning|     PMP-110|         Pumps|          922|           952|             49|              17|    265.29|        58.28|          4.41|        Reject|              No|    Charan|
|    PR0000064|     2026-10-21|    PL05|     MC022|     OP0267|Evening|     CTL-230|   Controllers|          805|           794|             16|              38|    189.94|        76.15|          3.55|          Pass|              No|     Anita|
|    PR0000067|     2026-05-08|    PL05|     MC022|     OP0311|Morning|     VLV-320|        Valves|          384|           362|             11|              54|     80.43|        56.44|          4.21|        Reject|              No|     Gopal|
|    PR0000073|     2026-10-16|    PL02|     MC010|     OP0580|Evening|     PMP-210|         Pumps|          973|           979|             13|              13|    475.51|        62.22|          5.32|        Rework|              No|    Harini|
|    PR0000080|     2026-06-10|    PL01|     MC003|     OP0214|  Night|     CTL-130|   Controllers|          948|           821|             49|              20|    188.65|        62.68|          2.85|        Reject|              No|     Anita|
|    PR0000089|     2026-09-20|    PL03|     MC014|     OP0375|  Night|     PMP-210|         Pumps|         1133|           971|             22|              14|    294.73|         NULL|          4.97|        Reject|              No|     Anita|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 10 rows

**2. Creating DataFrames**

Create a small DataFrame manually containing: plant_id, plant_name, city

In [ ]:
plant_data = [(1, "Plant Alpha", "Hyderabad"),
              (2, "Plant Beta", "Chennai"),
              (3, "Plant Gamma", "Pune")]

1. Create it using a list of tuples.

In [ ]:
small_df = spark.createDataFrame(plant_data)

2. Create it with explicit column names.

In [ ]:
small_df = spark.createDataFrame(plant_data, ["plant_id", "plant_name", "city"])

3. Create another version using StructType.

In [ ]:
from pyspark.sql.types import StructType, StructField, IntegerType, StringType

schema = StructType([
    StructField("plant_id", IntegerType(), True),
    StructField("plant_name", StringType(), True),
    StructField("city", StringType(), True)
])

4. Print the schema.

In [ ]:
small_df_st = spark.createDataFrame(plant_data, schema)
small_df_st.printSchema()

root
 |-- plant_id: integer (nullable = true)
 |-- plant_name: string (nullable = true)
 |-- city: string (nullable = true)

5. Add a constant column called country = India.

In [ ]:
from pyspark.sql.functions import lit
small_df_st = small_df_st.withColumn("country", lit("India")).show()

+--------+-----------+---------+-------+
|plant_id| plant_name|     city|country|
+--------+-----------+---------+-------+
|       1|Plant Alpha|Hyderabad|  India|
|       2| Plant Beta|  Chennai|  India|
|       3|Plant Gamma|     Pune|  India|
+--------+-----------+---------+-------+

**3. Pandas DataFrame.**

In [ ]:
import pandas as pd
pdf = pd.read_csv("manufacturing_production_120k.csv")

1. Display first 5 rows.

In [ ]:
print(pdf.head())

  production_id production_date plant_id machine_id operator_id    shift  \
0     PR0000001      2026-08-07     PL03      MC011      OP0275  Evening
1     PR0000002      2026-08-03     PL04      MC019      OP0489  Morning
2     PR0000003      2026-05-20     PL01      MC002      OP0189  Evening
3     PR0000004      2026-01-15     PL03      MC013      OP0076  Morning
4     PR0000005      2026-09-21     PL04      MC020      OP0501  Morning

  product_code product_family  units_planned  units_produced  defective_units  \
0      MTR-100         Motors           1060             993               30
1      CTL-330    Controllers            809             836                0
2      MTR-300         Motors            442             380               17
3      PMP-210          Pumps            787             720                7
4      PMP-110          Pumps            344             296                7

   downtime_minutes  energy_kwh  temperature_c  vibration_mm_s quality_status  \
0              34.0      388.11          61.40            3.88         Rework
1               0.0      398.58          64.37            2.28         Reject
2              15.0      183.34          54.13            4.66         Reject
3              39.0      217.61          64.47             NaN         Rework
4              49.0      115.47          72.59            3.21           Pass

  maintenance_flag supervisor
0               No     Charan
1               No      Farah
2               No      Deepa
3               No      Farah
4               No      Deepa

2. Display last 5 rows.

In [ ]:
print(pdf.tail())

       production_id production_date plant_id machine_id operator_id    shift  \
119995     PR0119996      2026-07-13     PL05      MC022      OP0193  Evening
119996     PR0119997      2026-04-26     PL05      MC024      OP0124  Evening
119997     PR0119998      2026-02-01     PL06      MC027      OP0051  Evening
119998     PR0119999      2026-01-17     PL01      MC001      OP0452  Evening
119999     PR0120000      2026-08-16     PL02      MC007      OP0420  Morning

       product_code product_family  units_planned  units_produced  \
119995      MTR-200         Motors            435             399
119996      CTL-130    Controllers            813             777
119997      VLV-120         Valves            650             597
119998      MTR-300         Motors            887             899
119999      MTR-200         Motors            547             477

        defective_units  downtime_minutes  energy_kwh  temperature_c  \
119995                1              73.0      126.07          62.79
119996                8              49.0      318.22          63.05
119997               13               0.0      269.46          60.52
119998               22              21.0      184.62          64.89
119999                4              43.0      107.95          62.50

        vibration_mm_s quality_status maintenance_flag supervisor
119995            5.73         Rework               No     Bharat
119996            3.53           Pass               No      Irfan
119997            3.81           Pass               No     Bharat
119998            5.20           Pass              Yes      Farah
119999            3.97           Pass               No      Farah

3. Display shape.

In [ ]:
print(pdf.shape)

(120000, 18)

4. Display column names.

In [ ]:
print(pdf.columns)

Index(['production_id', 'production_date', 'plant_id', 'machine_id',
       'operator_id', 'shift', 'product_code', 'product_family',
       'units_planned', 'units_produced', 'defective_units',
       'downtime_minutes', 'energy_kwh', 'temperature_c', 'vibration_mm_s',
       'quality_status', 'maintenance_flag', 'supervisor'],
      dtype='object')

5. Display datatypes.

In [ ]:
print(pdf.dtypes)

production_id        object
production_date      object
plant_id             object
machine_id           object
operator_id          object
shift                object
product_code         object
product_family       object
units_planned         int64
units_produced        int64
defective_units       int64
downtime_minutes    float64
energy_kwh          float64
temperature_c       float64
vibration_mm_s      float64
quality_status       object
maintenance_flag     object
supervisor           object
dtype: object

6. Select plant_id , machine_id , units_produced.

In [ ]:
pdf[["plant_id", "machine_id", "units_produced"]].head()

  plant_id machine_id  units_produced
0     PL03      MC011             993
1     PL04      MC019             836
2     PL01      MC002             380
3     PL03      MC013             720
4     PL04      MC020             296

7. Rename units_produced to production_output.

In [ ]:
pdf_renamed = pdf.rename(columns={"units_produced": "production_output"})
pdf_renamed.head()

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,production_output,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0000001,2026-08-07,PL03,MC011,OP0275,Evening,MTR-100,Motors,1060,993,30,34.0,388.11,61.40,3.88,Rework,No,Charan
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
3,PR0000004,2026-01-15,PL03,MC013,OP0076,Morning,PMP-210,Pumps,787,720,7,39.0,217.61,64.47,NaN,Rework,No,Farah
4,PR0000005,2026-09-21,PL04,MC020,OP0501,Morning,PMP-110,Pumps,344,296,7,49.0,115.47,72.59,3.21,Pass,No,Deepa

8. Filter rows where quality_status == "Reject".

In [ ]:
print(pdf.filter(pdf["quality_status"] == "Reject").head())

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

9. Filter rows where temperature is greater than 75.

In [ ]:
print(pdf.filter(pdf["temperature_c"] > 75).head())

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

10. Filter Night-shift production from Hyderabad plant.

In [ ]:
plant_pdf = pd.read_csv("plant_master.csv")
hyderabad_plant = plant_pdf[plant_pdf["city"] == "Hyderabad"]
print(pdf[(pdf["shift"] == "Night") & (pdf["plant_id"].isin(hyderabad_plant["plant_id"]))].head())

    production_id production_date plant_id machine_id operator_id  shift  \
29      PR0000030      2026-09-18     PL01      MC004      OP0266  Night
38      PR0000039      2026-07-17     PL01      MC002      OP0220  Night
62      PR0000063      2026-02-18     PL01      MC002      OP0390  Night
79      PR0000080      2026-06-10     PL01      MC003      OP0214  Night
145     PR0000146      2026-08-19     PL01      MC005      OP0088  Night

    product_code product_family  units_planned  units_produced  \
29       VLV-320         Valves            358             359
38       VLV-120         Valves            260             265
62       VLV-120         Valves            656             665
79       CTL-130    Controllers            948             821
145      VLV-120         Valves           1156             969

     defective_units  downtime_minutes  energy_kwh  temperature_c  \
29                 1              19.0      107.98          72.00
38                 0               2.0      127.18          51.87
62                 0              44.0      311.80          58.34
79                49              20.0      188.65          62.68
145                0               9.0      501.65          67.41

     vibration_mm_s quality_status maintenance_flag supervisor
29             1.73           Pass               No     Bharat
38             3.41           Pass               No      Irfan
62             2.00           Pass               No      Deepa
79             2.85         Reject               No      Anita
145            5.76         Rework               No     Bharat

**4. Dask DataFrame**

In [ ]:
import dask.dataframe as dd
import time
ddf = dd.read_csv("manufacturing_production_120k.csv")

1. Display first records using head().

In [ ]:
ddf = dd.read_csv("manufacturing_production_120k.csv", dtype={'downtime_minutes': 'float64'})
print(ddf.head())

  production_id production_date plant_id machine_id operator_id    shift  \
0     PR0000001      2026-08-07     PL03      MC011      OP0275  Evening
1     PR0000002      2026-08-03     PL04      MC019      OP0489  Morning
2     PR0000003      2026-05-20     PL01      MC002      OP0189  Evening
3     PR0000004      2026-01-15     PL03      MC013      OP0076  Morning
4     PR0000005      2026-09-21     PL04      MC020      OP0501  Morning

  product_code product_family  units_planned  units_produced  defective_units  \
0      MTR-100         Motors           1060             993               30
1      CTL-330    Controllers            809             836                0
2      MTR-300         Motors            442             380               17
3      PMP-210          Pumps            787             720                7
4      PMP-110          Pumps            344             296                7

   downtime_minutes  energy_kwh  temperature_c  vibration_mm_s quality_status  \
0              34.0      388.11          61.40            3.88         Rework
1               0.0      398.58          64.37            2.28         Reject
2              15.0      183.34          54.13            4.66         Reject
3              39.0      217.61          64.47             NaN         Rework
4              49.0      115.47          72.59            3.21           Pass

  maintenance_flag supervisor
0               No     Charan
1               No      Farah
2               No      Deepa
3               No      Farah
4               No      Deepa

2. Find number of partitions.

In [ ]:
print(ddf.npartitions)

1

3. Select plant_id , product_family , units_produced.

In [ ]:
selected_columns = ddf[["plant_id", "product_family", "units_produced"]]
print(selected_columns.head())

  plant_id product_family  units_produced
0     PL03         Motors             993
1     PL04    Controllers             836
2     PL01         Motors             380
3     PL03          Pumps             720
4     PL04          Pumps             296

4. Filter rejected production records.

In [ ]:
rejected_records = ddf[ddf["quality_status"] == "Reject"]
print(rejected_records.head())

   production_id production_date plant_id machine_id operator_id    shift  \
1      PR0000002      2026-08-03     PL04      MC019      OP0489  Morning
2      PR0000003      2026-05-20     PL01      MC002      OP0189  Evening
7      PR0000008      2026-08-17     PL02      MC009      OP0106    Night
9      PR0000010      2026-02-13     PL02      MC006      OP0593  Evening
21     PR0000022      2026-03-03     PL02      MC009      OP0294  Evening

   product_code product_family  units_planned  units_produced  \
1       CTL-330    Controllers            809             836
2       MTR-300         Motors            442             380
7       VLV-320         Valves            862             895
9       CTL-230    Controllers            532             527
21      MTR-300         Motors            623             560

    defective_units  downtime_minutes  energy_kwh  temperature_c  \
1                 0               0.0      398.58          64.37
2                17              15.0      183.34          54.13
7                51              77.0      266.06          57.10
9                26              64.0      112.17          60.96
21               23              14.0      217.69          55.23

    vibration_mm_s quality_status maintenance_flag supervisor
1             2.28         Reject               No      Farah
2             4.66         Reject               No      Deepa
7             1.34         Reject               No      Irfan
9             3.48         Reject               No      Gopal
21            3.28         Reject              Yes      Farah

5. Calculate average units produced by plant.

In [ ]:
average_units_by_plant = ddf.groupby("plant_id")["units_produced"].mean().compute()
print(average_units_by_plant)

plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64

6. Calculate total defects by product family.

In [ ]:
defects_by_product_family = ddf.groupby("product_family")["defective_units"].sum().compute()
print(defects_by_product_family)

product_family
Controllers    507781
Motors         505287
Pumps          507864
Valves         509312
Name: defective_units, dtype: int64

7. Use .compute() to obtain the final result.

In [ ]:
# The result is already computed and is a Pandas Series, so we print it directly
print(average_units_by_plant)
print(defects_by_product_family)

plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64
product_family
Controllers    507781
Motors         505287
Pumps          507864
Valves         509312
Name: defective_units, dtype: int64

8. Compare doing the same aggregation in Pandas and Dask.

In [ ]:
t0 = time.time(); p_res = pdf.groupby("plant_id")["units_produced"].mean(); t_pd = time.time() - t0
t0 = time.time(); d_res = ddf.groupby("plant_id")["units_produced"].mean().compute(); t_dd = time.time() - t0
print(f"Pandas: {t_pd:.3f}s | Dask: {t_dd:.3f}s")

Pandas: 0.015s | Dask: 0.388s

**5. Manipulating DataFrames**

In [ ]:
df = spark.read.csv(
"manufacturing_production_120k.csv",
    header=True,
    inferSchema=True
)

In [ ]:
df.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

1. Create: production_efficiency =
units_produced / units_planned * 100

In [ ]:
df2 = df.withColumn("production_efficiency", (df["units_produced"] / df["units_planned"]) * 100)
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_efficiency|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|    93.67924528301886|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|   103.33745364647713|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|    85.97285067873304|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|     91.4866581956798|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    86.04651162790698|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|    82.98538622129436|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|    81.97424892703863|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|   103.82830626450117|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    92.33226837060703|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|    99.06015037593986|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|    88.73483535528595|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|    98.77551020408163|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    86.35458167330677|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   101.78571428571428|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|    95.94843462246777|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    84.13793103448276|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|             83.59375|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|    86.69131238447319|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|    99.73753280839895|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|    88.69969040247679|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
only showing top 20 rows

2. Create: good_units =
units_produced - defective_units

In [ ]:
df2 = df2.withColumn("good_units", df2["units_produced"] - df2["defective_units"])
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_efficiency|good_units|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|    93.67924528301886|       963|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|   103.33745364647713|       836|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|    85.97285067873304|       363|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|     91.4866581956798|       713|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    86.04651162790698|       289|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|    82.98538622129436|       745|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|    81.97424892703863|       945|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|   103.82830626450117|       844|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    92.33226837060703|       281|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|    99.06015037593986|       501|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|    88.73483535528595|       498|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|    98.77551020408163|       945|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    86.35458167330677|       840|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   101.78571428571428|       450|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|    95.94843462246777|      1038|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    84.13793103448276|       732|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|             83.59375|       935|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|    86.69131238447319|       451|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|    99.73753280839895|       364|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|    88.69969040247679|       560|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+----------+
only showing top 20 rows

3. Add: country = India

In [ ]:
df2 = df2.withColumn("country", lit("India"))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|    93.67924528301886|       963|  India|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|   103.33745364647713|       836|  India|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|    85.97285067873304|       363|  India|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|     91.4866581956798|       713|  India|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    86.04651162790698|       289|  India|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|    82.98538622129436|       745|  India|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|    81.97424892703863|       945|  India|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|   103.82830626450117|       844|  India|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    92.33226837060703|       281|  India|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|    99.06015037593986|       501|  India|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|    88.73483535528595|       498|  India|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|    98.77551020408163|       945|  India|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|    95.94843462246777|      1038|  India|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|             83.59375|       935|  India|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|    86.69131238447319|       451|  India|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|    99.73753280839895|       364|  India|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|    88.69969040247679|       560|  India|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
only showing top 20 rows

4. Rename energy_kwh to energy_consumed

In [ ]:
df2 = df2.withColumnRenamed("energy_kwh", "energy_consumed")
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|         388.11|         61.4|          3.88|        Rework|              No|    Charan|    93.67924528301886|       963|  India|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|         398.58|        64.37|          2.28|        Reject|              No|     Farah|   103.33745364647713|       836|  India|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|         183.34|        54.13|          4.66|        Reject|              No|     Deepa|    85.97285067873304|       363|  India|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|         217.61|        64.47|          NULL|        Rework|              No|     Farah|     91.4866581956798|       713|  India|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|         115.47|        72.59|          3.21|          Pass|              No|     Deepa|    86.04651162790698|       289|  India|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|         290.26|        64.91|          2.77|        Rework|              No|     Gopal|    82.98538622129436|       745|  India|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|         355.56|        62.76|          2.89|          Pass|              No|     Gopal|    81.97424892703863|       945|  India|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|         266.06|         57.1|          1.34|        Reject|              No|     Irfan|   103.82830626450117|       844|  India|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|          87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    92.33226837060703|       281|  India|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|         112.17|        60.96|          3.48|        Reject|              No|     Gopal|    99.06015037593986|       501|  India|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|          127.0|        52.81|          3.46|          Pass|              No|    Bharat|    88.73483535528595|       498|  India|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|         377.97|        69.79|          3.43|        Rework|              No|     Gopal|    98.77551020408163|       945|  India|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|         388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|         108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|         239.64|        76.39|          2.81|          Pass|              No|     Deepa|    95.94843462246777|      1038|  India|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|         289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|         347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|             83.59375|       935|  India|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|         241.05|        59.91|          3.87|          Pass|              No|     Farah|    86.69131238447319|       451|  India|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|         137.99|        62.23|          4.29|          Pass|              No|     Deepa|    99.73753280839895|       364|  India|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|         277.73|        76.92|          2.35|          Pass|              No|     Irfan|    88.69969040247679|       560|  India|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
only showing top 20 rows

5. Convert units_produced to double.

In [ ]:
df2 = df2.withColumn("units_produced", df2["units_produced"].cast("double"))
df2.show()
print(df2.dtypes)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|         993.0|             30|              34|         388.11|         61.4|          3.88|        Rework|              No|    Charan|    93.67924528301886|       963|  India|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|         836.0|              0|               0|         398.58|        64.37|          2.28|        Reject|              No|     Farah|   103.33745364647713|       836|  India|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|         380.0|             17|              15|         183.34|        54.13|          4.66|        Reject|              No|     Deepa|    85.97285067873304|       363|  India|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|         720.0|              7|              39|         217.61|        64.47|          NULL|        Rework|              No|     Farah|     91.4866581956798|       713|  India|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|         296.0|              7|              49|         115.47|        72.59|          3.21|          Pass|              No|     Deepa|    86.04651162790698|       289|  India|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|         795.0|             50|              44|         290.26|        64.91|          2.77|        Rework|              No|     Gopal|    82.98538622129436|       745|  India|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|         955.0|             10|               5|         355.56|        62.76|          2.89|          Pass|              No|     Gopal|    81.97424892703863|       945|  India|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|         895.0|             51|              77|         266.06|         57.1|          1.34|        Reject|              No|     Irfan|   103.82830626450117|       844|  India|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|         289.0|              8|              16|          87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    92.33226837060703|       281|  India|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|         527.0|             26|              64|         112.17|        60.96|          3.48|        Reject|              No|     Gopal|    99.06015037593986|       501|  India|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|         512.0|             14|              32|          127.0|        52.81|          3.46|          Pass|              No|    Bharat|    88.73483535528595|       498|  India|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|         968.0|             23|              38|         377.97|        69.79|          3.43|        Rework|              No|     Gopal|    98.77551020408163|       945|  India|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|         867.0|             27|              66|         388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|         456.0|              6|               6|         108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|        1042.0|              4|             172|         239.64|        76.39|          2.81|          Pass|              No|     Deepa|    95.94843462246777|      1038|  India|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|         732.0|              0|              13|         289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|         963.0|             28|              91|         347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|             83.59375|       935|  India|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|         469.0|             18|              36|         241.05|        59.91|          3.87|          Pass|              No|     Farah|    86.69131238447319|       451|  India|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|         380.0|             16|              25|         137.99|        62.23|          4.29|          Pass|              No|     Deepa|    99.73753280839895|       364|  India|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|         573.0|             13|              64|         277.73|        76.92|          2.35|          Pass|              No|     Irfan|    88.69969040247679|       560|  India|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+
only showing top 20 rows
[('production_id', 'string'), ('production_date', 'date'), ('plant_id', 'string'), ('machine_id', 'string'), ('operator_id', 'string'), ('shift', 'string'), ('product_code', 'string'), ('product_family', 'string'), ('units_planned', 'int'), ('units_produced', 'double'), ('defective_units', 'int'), ('downtime_minutes', 'int'), ('energy_consumed', 'double'), ('temperature_c', 'double'), ('vibration_mm_s', 'double'), ('quality_status', 'string'), ('maintenance_flag', 'string'), ('supervisor', 'string'), ('production_efficiency', 'double'), ('good_units', 'int'), ('country', 'string')]

6. Create defect_percentage.

In [ ]:
df2 = df2.withColumn("defect_percentage", (df2["defective_units"] / df2["units_produced"]) * 100)
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|         993.0|             30|              34|         388.11|         61.4|          3.88|        Rework|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|         836.0|              0|               0|         398.58|        64.37|          2.28|        Reject|              No|     Farah|   103.33745364647713|       836|  India|               0.0|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|         380.0|             17|              15|         183.34|        54.13|          4.66|        Reject|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|         720.0|              7|              39|         217.61|        64.47|          NULL|        Rework|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|         296.0|              7|              49|         115.47|        72.59|          3.21|          Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|         795.0|             50|              44|         290.26|        64.91|          2.77|        Rework|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|         955.0|             10|               5|         355.56|        62.76|          2.89|          Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|         895.0|             51|              77|         266.06|         57.1|          1.34|        Reject|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|         289.0|              8|              16|          87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    92.33226837060703|       281|  India| 2.768166089965398|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|         527.0|             26|              64|         112.17|        60.96|          3.48|        Reject|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|         512.0|             14|              32|          127.0|        52.81|          3.46|          Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|         968.0|             23|              38|         377.97|        69.79|          3.43|        Rework|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|         867.0|             27|              66|         388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|         456.0|              6|               6|         108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|        1042.0|              4|             172|         239.64|        76.39|          2.81|          Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|         732.0|              0|              13|         289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|         963.0|             28|              91|         347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|         469.0|             18|              36|         241.05|        59.91|          3.87|          Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|         380.0|             16|              25|         137.99|        62.23|          4.29|          Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|         573.0|             13|              64|         277.73|        76.92|          2.35|          Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+
only showing top 20 rows

7. Create energy_per_unit.

In [ ]:
df2 = df2.withColumn("energy_per_unit", df2["energy_consumed"] / df2["units_produced"])
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|         993.0|             30|              34|         388.11|         61.4|          3.88|        Rework|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|         836.0|              0|               0|         398.58|        64.37|          2.28|        Reject|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|         380.0|             17|              15|         183.34|        54.13|          4.66|        Reject|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|         720.0|              7|              39|         217.61|        64.47|          NULL|        Rework|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|         296.0|              7|              49|         115.47|        72.59|          3.21|          Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|         795.0|             50|              44|         290.26|        64.91|          2.77|        Rework|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|         955.0|             10|               5|         355.56|        62.76|          2.89|          Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|         895.0|             51|              77|         266.06|         57.1|          1.34|        Reject|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|         289.0|              8|              16|          87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|         527.0|             26|              64|         112.17|        60.96|          3.48|        Reject|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|         512.0|             14|              32|          127.0|        52.81|          3.46|          Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|         968.0|             23|              38|         377.97|        69.79|          3.43|        Rework|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|         867.0|             27|              66|         388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|         456.0|              6|               6|         108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|        1042.0|              4|             172|         239.64|        76.39|          2.81|          Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|         732.0|              0|              13|         289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|         963.0|             28|              91|         347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|         469.0|             18|              36|         241.05|        59.91|          3.87|          Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|         380.0|             16|              25|         137.99|        62.23|          4.29|          Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|         573.0|             13|              64|         277.73|        76.92|          2.35|          Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
only showing top 20 rows

8. Select only the transformed columns.

In [ ]:
df2.select("production_efficiency", "good_units", "country", "energy_consumed", "defect_percentage", "energy_per_unit").show()

+---------------------+----------+-------+---------------+------------------+-------------------+
|production_efficiency|good_units|country|energy_consumed| defect_percentage|    energy_per_unit|
+---------------------+----------+-------+---------------+------------------+-------------------+
|    93.67924528301886|       963|  India|         388.11|3.0211480362537766|0.39084592145015107|
|   103.33745364647713|       836|  India|         398.58|               0.0| 0.4767703349282296|
|    85.97285067873304|       363|  India|         183.34| 4.473684210526316|0.48247368421052633|
|     91.4866581956798|       713|  India|         217.61|0.9722222222222222|0.30223611111111115|
|    86.04651162790698|       289|  India|         115.47| 2.364864864864865| 0.3901013513513513|
|    82.98538622129436|       745|  India|         290.26| 6.289308176100629| 0.3651069182389937|
|    81.97424892703863|       945|  India|         355.56|1.0471204188481675|0.37231413612565445|
|   103.82830626450117|       844|  India|         266.06| 5.698324022346369| 0.2972737430167598|
|    92.33226837060703|       281|  India|          87.62| 2.768166089965398| 0.3031833910034602|
|    99.06015037593986|       501|  India|         112.17| 4.933586337760911| 0.2128462998102467|
|    88.73483535528595|       498|  India|          127.0|          2.734375|        0.248046875|
|    98.77551020408163|       945|  India|         377.97|  2.37603305785124| 0.3904648760330579|
|    86.35458167330677|       840|  India|         388.61|3.1141868512110724| 0.4482237600922722|
|   101.78571428571428|       450|  India|         108.83|1.3157894736842104|0.23866228070175438|
|    95.94843462246777|      1038|  India|         239.64|0.3838771593090211|0.22998080614203453|
|    84.13793103448276|       732|  India|         289.55|               0.0| 0.3955601092896175|
|             83.59375|       935|  India|         347.34| 2.907580477673936|0.36068535825545167|
|    86.69131238447319|       451|  India|         241.05|3.8379530916844353| 0.5139658848614073|
|    99.73753280839895|       364|  India|         137.99|4.2105263157894735|0.36313157894736847|
|    88.69969040247679|       560|  India|         277.73|2.2687609075043627|  0.484694589877836|
+---------------------+----------+-------+---------------+------------------+-------------------+
only showing top 20 rows

**6. Dropping Data**

1. Drop supervisor.

In [ ]:
df.drop("supervisor").show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
only showing top 20 rows

2. Drop supervisor and maintenance_flag.

In [ ]:
df.drop("supervisor", "maintenance_flag").show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
only showing top 20 rows

3. Remove duplicate rows.

In [ ]:
df.dropDuplicates().count()

120000

4. Keep one record per production_id.

In [ ]:
df.dropDuplicates(["production_id"]).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000025|     2026-07-28|    PL04|     MC017|     OP0636|Evening|     VLV-220|        Valves|         1139|          1126|             38|              13|    332.97|        58.08|          4.15|          Pass|              No|     Irfan|
|    PR0000026|     2026-04-09|    PL01|     MC001|     OP0604|Evening|     MTR-300|        Motors|          643|           663|             20|              26|    180.36|        63.77|          4.49|          Pass|             Yes|    Charan|
|    PR0000031|     2026-01-04|    PL01|     MC003|     OP0524|Evening|     PMP-210|         Pumps|          762|           776|             49|              28|    238.12|         66.8|          3.09|        Reject|              No|    Bharat|
|    PR0000032|     2026-05-28|    PL06|     MC030|     OP0074|  Night|     CTL-230|   Controllers|          819|           773|             11|              27|     354.3|        63.51|          3.18|          Pass|              No|     Deepa|
|    PR0000036|     2026-07-13|    PL04|     MC020|     OP0559|Evening|     MTR-200|        Motors|          576|           578|              0|              38|    267.36|        70.28|          2.69|          Pass|              No|     Farah|
|    PR0000037|     2026-10-12|    PL06|     MC026|     OP0163|Morning|     MTR-100|        Motors|          633|           626|             15|              56|    173.17|        64.63|           3.7|          Pass|              No|     Irfan|
|    PR0000038|     2026-02-23|    PL02|     MC008|     OP0114|  Night|     MTR-300|        Motors|          864|           867|              6|              38|    335.24|         53.7|           3.0|          Pass|              No|     Anita|
|    PR0000039|     2026-07-17|    PL01|     MC002|     OP0220|  Night|     VLV-120|        Valves|          260|           265|              0|               2|    127.18|        51.87|          3.41|          Pass|              No|     Irfan|
|    PR0000041|     2026-05-14|    PL02|     MC009|     OP0192|Morning|     PMP-310|         Pumps|          711|           664|             32|              60|    335.84|        57.87|           3.2|          Pass|             Yes|     Irfan|
|    PR0000046|     2026-04-02|    PL06|     MC027|     OP0484|Morning|     VLV-120|        Valves|          847|           778|             19|             145|    381.88|        63.42|          2.94|        Reject|              No|     Anita|
|    PR0000047|     2026-01-22|    PL06|     MC028|     OP0512|Evening|     PMP-110|         Pumps|          956|           882|              4|             118|     247.4|         NULL|          2.52|          Pass|              No|    Charan|
|    PR0000048|     2026-03-08|    PL03|     MC015|     OP0110|Morning|     CTL-230|   Controllers|          858|           810|              0|               0|    250.54|        58.93|          4.04|          Pass|              No|    Bharat|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

5. Remove records where operator ID is missing.

In [ ]:
df.na.drop(subset=["operator_id"]).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

6. Remove rows where both temperature and vibration are missing.

In [ ]:
df.na.drop(subset=["temperature_c", "vibration_mm_s"], how="all").show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

7. Display unique product families.

In [ ]:
df.select("product_family").distinct().show()

+--------------+
|product_family|
+--------------+
|         Pumps|
|        Valves|
|   Controllers|
|        Motors|
+--------------+

8. Display unique plant-machine combinations.

In [ ]:
df.select("plant_id", "machine_id").distinct().show()

+--------+----------+
|plant_id|machine_id|
+--------+----------+
|    PL01|     MC001|
|    PL01|     MC004|
|    PL04|     MC019|
|    PL04|     MC017|
|    PL05|     MC022|
|    PL04|     MC018|
|    PL01|     MC003|
|    PL06|     MC029|
|    PL02|     MC007|
|    PL03|     MC013|
|    PL06|     MC030|
|    PL04|     MC020|
|    PL05|     MC021|
|    PL01|     MC005|
|    PL02|     MC010|
|    PL04|     MC016|
|    PL06|     MC027|
|    PL02|     MC006|
|    PL01|     MC002|
|    PL06|     MC028|
+--------+----------+
only showing top 20 rows

**7. Sorting**

In [ ]:
from pyspark.sql.functions import asc, desc

1. Sort by units produced ascending.

In [ ]:
from pyspark.sql.functions import col
df.sort(col("units_produced").asc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|
|    PR0059668|     2026-05-01|    PL05|     MC021|     OP0067|  Night|     CTL-130|   Controllers|          250|           205|             11|              54|     89.67|        58.31|          2.69|          Pass|              No|     Anita|
|    PR0079337|     2026-05-05|    PL04|     MC018|     OP0623|Evening|     PMP-210|         Pumps|          251|           206|              0|               0|     77.66|        67.78|          2.36|        Rework|              No|     Irfan|
|    PR0013719|     2026-04-30|    PL03|     MC014|     OP0340|Morning|     MTR-200|        Motors|          250|           206|              5|              82|     62.29|        55.57|           2.4|          Pass|              No|    Harini|
|    PR0087182|     2026-09-03|    PL04|     MC019|     OP0196|Evening|     CTL-330|   Controllers|          250|           206|              4|              13|     98.25|        59.27|          6.99|        Reject|             Yes|     Irfan|
|    PR0015709|     2026-03-09|    PL05|     MC021|     OP0538|  Night|     VLV-220|        Valves|          251|           206|              9|               3|     87.29|        68.35|          1.27|        Reject|              No|    Bharat|
|    PR0115075|     2026-10-03|    PL04|     MC019|     OP0014|  Night|     CTL-130|   Controllers|          251|           206|              1|              66|     79.31|         78.2|          4.21|        Rework|              No|    Bharat|
|    PR0026161|     2026-04-28|    PL05|     MC025|     OP0617|Evening|     PMP-210|         Pumps|          251|           206|              2|              42|     74.72|        76.08|          3.96|        Reject|             Yes|     Gopal|
|    PR0030899|     2026-05-24|    PL01|     MC004|     OP0380|Evening|     VLV-120|        Valves|          252|           206|             12|              12|     75.94|        50.77|          3.34|        Rework|              No|     Farah|
|    PR0039880|     2026-01-04|    PL01|     MC005|     OP0034|Evening|     PMP-210|         Pumps|          250|           206|              0|              38|      50.0|        64.38|          2.33|        Rework|              No|     Deepa|
|    PR0071924|     2026-05-26|    PL01|     MC003|     OP0120|  Night|     PMP-210|         Pumps|          251|           206|              9|              40|      50.0|        52.13|          2.54|          Pass|              No|     Irfan|
|    PR0107410|     2026-09-29|    PL03|     MC012|     OP0237|Evening|     VLV-120|        Valves|          252|           207|              8|              36|     99.97|        61.39|          3.94|          Pass|              No|     Deepa|
|    PR0013195|     2026-03-18|    PL05|     MC021|     OP0182|  Night|     PMP-310|         Pumps|          253|           207|              4|              18|     59.88|        73.69|          2.98|          Pass|              No|     Irfan|
|    PR0118888|     2026-06-01|    PL04|     MC019|     OP0350|Morning|     MTR-300|        Motors|          250|           207|              3|              29|      50.0|        53.55|          4.18|          Pass|              No|     Farah|
|    PR0020293|     2026-08-08|    PL03|     MC014|     OP0567|Evening|     CTL-130|   Controllers|          253|           207|              5|              37|      50.0|        64.89|          1.81|          Pass|              No|     Deepa|
|    PR0028542|     2026-04-10|    PL04|     MC020|     OP0325|Evening|     CTL-230|   Controllers|          251|           207|              8|              18|     93.84|         64.9|          1.55|          Pass|              No|     Anita|
|    PR0035230|     2026-02-05|    PL06|     MC029|     OP0479|  Night|     VLV-120|        Valves|          253|           207|              6|               0|    107.62|         NULL|          3.56|        Rework|              No|     Anita|
|    PR0097162|     2026-09-02|    PL06|     MC027|     OP0139|  Night|     MTR-100|        Motors|          252|           208|              6|              11|     92.62|        61.86|          1.74|          Pass|              No|     Deepa|
|    PR0005895|     2026-09-15|    PL04|     MC018|     OP0322|  Night|     VLV-320|        Valves|          251|           208|              3|              33|     66.87|        49.32|          2.91|          Pass|              No|    Bharat|
|    PR0105232|     2026-08-26|    PL04|     MC018|     OP0505|Evening|     VLV-220|        Valves|          251|           208|              8|               0|      59.1|        57.55|          3.65|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

2. Sort units produced descending.

In [ ]:
df.sort(col("units_produced").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|
|    PR0033781|     2026-04-18|    PL05|     MC022|     OP0254|Evening|     PMP-310|         Pumps|         1200|          1238|             36|              41|    617.76|        72.83|           4.8|          Pass|              No|    Charan|
|    PR0098449|     2026-08-11|    PL05|     MC022|     OP0049|Morning|     PMP-110|         Pumps|         1198|          1238|             58|              47|    600.77|        63.45|          3.29|          Pass|              No|     Irfan|
|    PR0074297|     2026-05-20|    PL04|     MC019|     OP0142|Morning|     MTR-200|        Motors|         1195|          1238|             23|               0|     331.2|        66.75|           4.1|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

3. Sort highest defective units first.

In [ ]:
df.sort(col("defective_units").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0051359|     2026-09-16|    PL02|     MC009|     OP0181|Morning|     CTL-230|   Controllers|         1192|          1230|            108|               8|    555.34|        71.97|          2.09|        Rework|              No|     Irfan|
|    PR0108009|     2026-06-07|    PL05|     MC023|     OP0417|Morning|     CTL-230|   Controllers|         1061|          1067|            106|               0|    491.74|         NULL|          4.93|        Rework|             Yes|     Farah|
|    PR0067365|     2026-05-13|    PL01|     MC001|     OP0461|Evening|     MTR-100|        Motors|         1189|          1186|            103|               0|    373.15|        64.44|          4.27|        Reject|             Yes|     Farah|
|    PR0070440|     2026-05-23|    PL04|     MC018|     OP0033|  Night|     VLV-120|        Valves|         1133|          1124|            102|               0|    238.46|        71.28|          2.79|        Reject|              No|     Deepa|
|    PR0082514|     2026-03-18|    PL04|     MC017|     OP0007|Morning|     PMP-310|         Pumps|         1181|          1109|            100|              19|    331.99|        56.53|          2.97|        Reject|              No|     Anita|
|    PR0106744|     2026-04-27|    PL01|     MC003|     OP0094|Evening|     CTL-130|   Controllers|         1084|          1103|            100|               0|    465.02|        68.15|          2.18|        Rework|              No|    Charan|
|    PR0013103|     2026-05-06|    PL02|     MC009|     OP0159|Morning|     MTR-100|        Motors|         1042|           990|             97|              30|    196.72|        57.62|          3.46|        Rework|              No|    Harini|
|    PR0045241|     2026-01-04|    PL03|     MC013|     OP0202|Morning|     VLV-320|        Valves|         1197|          1231|             96|              23|    456.16|         63.5|          1.55|        Rework|              No|    Harini|
|    PR0103867|     2026-06-07|    PL04|     MC017|     OP0033|Morning|     PMP-310|         Pumps|         1088|          1095|             95|              29|    411.22|        62.63|           0.4|        Rework|              No|     Irfan|
|    PR0043427|     2026-02-04|    PL04|     MC017|     OP0003|Morning|     VLV-120|        Valves|         1170|          1196|             95|              19|    218.83|        65.99|          NULL|        Rework|              No|     Deepa|
|    PR0068424|     2026-07-18|    PL06|     MC027|     OP0609|Evening|     VLV-320|        Valves|         1052|          1073|             93|              52|    406.85|         57.3|          4.71|        Reject|             Yes|    Harini|
|    PR0014350|     2026-09-27|    PL05|     MC023|     OP0458|Evening|     CTL-330|   Controllers|         1120|          1128|             91|               7|    250.83|        61.73|          4.66|        Rework|              No|     Farah|
|    PR0068990|     2026-02-02|    PL01|     MC004|     OP0210|Evening|     CTL-230|   Controllers|         1136|          1104|             91|              47|    232.35|        61.59|          3.57|        Reject|              No|     Farah|
|    PR0078536|     2026-05-11|    PL03|     MC012|     OP0486|  Night|     PMP-110|         Pumps|         1141|          1095|             91|              51|    301.78|        62.09|          3.48|        Rework|              No|     Farah|
|    PR0039878|     2026-07-28|    PL05|     MC022|     OP0464|Evening|     MTR-100|        Motors|         1052|           990|             90|              14|    341.79|        57.54|           3.7|        Reject|              No|    Charan|
|    PR0082255|     2026-09-01|    PL02|     MC007|     OP0528|  Night|     VLV-320|        Valves|         1174|          1123|             89|              20|    314.99|        71.07|          0.83|        Rework|              No|     Gopal|
|    PR0085319|     2026-09-23|    PL05|     MC024|     OP0399|Morning|     VLV-120|        Valves|          973|           970|             89|              52|    390.03|         59.4|          1.64|        Rework|             Yes|     Irfan|
|    PR0027472|     2026-10-22|    PL04|     MC016|     OP0340|Morning|     CTL-330|   Controllers|         1100|           960|             88|              40|    341.48|        51.33|          4.22|        Rework|              No|    Harini|
|    PR0116375|     2026-01-06|    PL03|     MC015|     OP0318|  Night|     MTR-200|        Motors|         1174|          1206|             88|              68|    405.22|        57.62|          4.43|        Rework|              No|     Farah|
|    PR0064147|     2026-07-28|    PL01|     MC004|     OP0105|Evening|     MTR-100|        Motors|         1162|          1159|             88|               0|    297.53|        58.15|           0.4|        Rework|              No|     Gopal|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

4. Sort by plant and then production output descending.

In [ ]:
df.sort(col("plant_id").asc(), col("units_produced").desc()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|
|    PR0005192|     2026-09-08|    PL01|     MC002|     OP0075|Morning|     MTR-300|        Motors|         1195|          1236|             12|              49|    349.97|         81.8|          2.95|          Pass|              No|     Gopal|
|    PR0044516|     2026-10-10|    PL01|     MC002|     OP0513|Morning|     MTR-200|        Motors|         1200|          1236|             25|              37|    233.63|        75.95|          1.82|          Pass|              No|     Gopal|
|    PR0056319|     2026-06-07|    PL01|     MC002|     OP0453|Evening|     CTL-130|   Controllers|         1193|          1236|              4|              24|    617.25|        46.98|          4.71|          Pass|             Yes|     Farah|
|    PR0006350|     2026-02-04|    PL01|     MC004|     OP0322|  Night|     PMP-110|         Pumps|         1193|          1234|             38|              27|    585.43|        59.48|          2.58|          Pass|             Yes|     Anita|
|    PR0046906|     2026-04-21|    PL01|     MC005|     OP0649|Evening|     CTL-230|   Controllers|         1199|          1233|             75|              42|    392.44|        69.03|          2.04|        Reject|             Yes|     Gopal|
|    PR0046582|     2026-07-18|    PL01|     MC002|     OP0040|  Night|     MTR-100|        Motors|         1190|          1230|              3|              34|    232.68|        51.69|          4.69|        Reject|              No|     Irfan|
|    PR0097172|     2026-01-29|    PL01|     MC002|     OP0257|  Night|     PMP-310|         Pumps|         1198|          1229|             55|              30|    444.46|        71.27|          4.99|        Rework|              No|     Deepa|
|    PR0024941|     2026-04-21|    PL01|     MC002|     OP0101|Evening|     VLV-120|        Valves|         1193|          1229|             25|             117|    310.61|        65.69|          2.64|        Reject|              No|    Harini|
|    PR0088933|     2026-03-04|    PL01|     MC003|     OP0492|Morning|     MTR-300|        Motors|         1190|          1229|             51|              34|    267.82|        78.75|          4.76|        Rework|              No|    Bharat|
|    PR0048075|     2026-03-05|    PL01|     MC005|     OP0171|Evening|     PMP-310|         Pumps|         1196|          1228|             14|              12|    569.62|        54.97|          4.02|          Pass|              No|    Harini|
|    PR0083644|     2026-07-13|    PL01|     MC005|     OP0043|Evening|     PMP-310|         Pumps|         1188|          1228|             16|              30|    533.46|        70.21|          4.53|          Pass|              No|    Bharat|
|    PR0002284|     2026-08-31|    PL01|     MC004|     OP0639|Evening|     PMP-110|         Pumps|         1192|          1227|             30|               0|    438.15|        66.08|          3.65|        Rework|              No|     Farah|
|    PR0109962|     2026-03-06|    PL01|     MC001|     OP0536|Evening|     MTR-300|        Motors|         1199|          1227|             16|              15|    280.96|        52.32|          2.04|          Pass|              No|     Gopal|
|    PR0012821|     2026-07-14|    PL01|     MC005|     OP0195|Morning|     CTL-130|   Controllers|         1192|          1226|              7|              58|     625.8|        57.83|          2.22|        Reject|              No|     Farah|
|    PR0119269|     2026-06-22|    PL01|     MC005|     OP0125|Evening|     MTR-200|        Motors|         1182|          1226|             21|              33|    268.92|        67.94|          2.68|        Reject|              No|     Farah|
|    PR0000300|     2026-05-07|    PL01|     MC003|     OP0478|Evening|     VLV-320|        Valves|         1181|          1226|             31|              35|    359.21|         69.8|          3.13|        Reject|              No|     Farah|
|    PR0083683|     2026-04-10|    PL01|     MC002|     OP0268|Evening|     MTR-200|        Motors|         1188|          1226|             16|              45|    455.05|        59.46|          3.55|          Pass|              No|     Anita|
|    PR0022084|     2026-01-26|    PL01|     MC004|     OP0396|Morning|     PMP-310|         Pumps|         1198|          1226|             38|              15|    617.55|        69.97|          3.97|        Reject|             Yes|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

5. Display the top 20 production runs.

In [ ]:
df.sort(col("units_produced").desc()).limit(20).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|
|    PR0098449|     2026-08-11|    PL05|     MC022|     OP0049|Morning|     PMP-110|         Pumps|         1198|          1238|             58|              47|    600.77|        63.45|          3.29|          Pass|              No|     Irfan|
|    PR0020622|     2026-09-20|    PL05|     MC021|     OP0580|Evening|     VLV-320|        Valves|         1191|          1238|             57|              32|     639.8|        69.02|          3.63|          Pass|              No|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+

6. Display the 10 runs with highest downtime.

In [ ]:
df.sort(col("downtime_minutes").desc()).limit(10).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0092818|     2026-02-16|    PL06|     MC027|     OP0016|Morning|     PMP-210|         Pumps|         1066|           907|              2|             281|    359.48|        54.03|           2.8|          Pass|              No|     Farah|
|    PR0045363|     2026-07-07|    PL02|     MC010|     OP0215|  Night|     CTL-330|   Controllers|          502|           463|              3|             278|    112.25|        72.69|          4.03|          Pass|              No|    Bharat|
|    PR0020842|     2026-04-28|    PL02|     MC008|     OP0003|  Night|     MTR-200|        Motors|         1004|           985|             24|             267|    326.53|        53.78|          3.82|        Reject|              No|    Harini|
|    PR0065023|     2026-02-11|    PL06|     MC029|     OP0249|Evening|     CTL-230|   Controllers|          708|           654|             23|             267|    220.98|         67.8|           4.8|          Pass|              No|     Deepa|
|    PR0068768|     2026-03-27|    PL03|     MC012|     OP0098|  Night|     MTR-200|        Motors|          958|           898|             15|             267|     172.3|        64.62|          4.59|          Pass|              No|     Farah|
|    PR0100950|     2026-01-16|    PL03|     MC012|     OP0076|Evening|     MTR-100|        Motors|          977|           900|             13|             263|     401.3|        66.18|          1.91|          Pass|              No|    Charan|
|    PR0041129|     2026-02-06|    PL01|     MC005|     OP0338|Morning|     PMP-110|         Pumps|          374|           361|              6|             263|    158.25|        71.94|          3.47|          Pass|              No|     Gopal|
|    PR0049997|     2026-08-30|    PL04|     MC019|     OP0337|  Night|     PMP-310|         Pumps|          584|           575|              7|             263|    292.82|        42.51|          5.13|          Pass|             Yes|     Farah|
|    PR0022495|     2026-06-18|    PL05|     MC022|     OP0619|Evening|     VLV-120|        Valves|         1172|          1141|             56|             262|     265.5|        53.16|          4.48|          Pass|              No|    Charan|
|    PR0112855|     2026-03-28|    PL02|     MC008|     OP0589|Morning|     MTR-100|        Motors|          319|           269|              2|             261|     92.92|         69.9|          2.57|          Pass|             Yes|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+

7. Find machines with the highest recorded vibration.

In [ ]:
df.sort(col("vibration_mm_s").desc()).limit(10).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0020211|     2026-10-08|    PL03|     MC012|     OP0283|  Night|     MTR-200|        Motors|          797|           820|             32|               0|    310.44|        54.91|          8.56|        Rework|             Yes|     Farah|
|    PR0109182|     2026-08-25|    PL06|     MC030|     OP0075|Morning|     PMP-110|         Pumps|          636|           624|              2|              34|     147.8|        65.99|          8.25|          Pass|             Yes|    Harini|
|    PR0107399|     2026-09-27|    PL06|     MC027|     OP0270|Morning|     MTR-300|        Motors|          612|           520|             13|               9|    228.61|        66.12|          7.85|        Rework|             Yes|     Farah|
|    PR0010851|     2026-01-08|    PL02|     MC010|     OP0070|Evening|     CTL-130|   Controllers|         1006|           966|             24|              58|    282.48|        66.08|           7.8|        Reject|             Yes|     Deepa|
|    PR0100446|     2026-04-23|    PL04|     MC018|     OP0364|Evening|     PMP-110|         Pumps|         1175|           985|             47|              42|    357.09|        63.15|          7.79|        Reject|             Yes|    Bharat|
|    PR0070661|     2026-03-06|    PL05|     MC024|     OP0309|Morning|     CTL-330|   Controllers|          839|           757|              7|              50|    307.23|        63.07|          7.77|          Pass|             Yes|     Irfan|
|    PR0008347|     2026-05-16|    PL03|     MC015|     OP0376|Evening|     VLV-220|        Valves|          352|           324|              0|              19|    120.89|        61.37|          7.76|        Reject|             Yes|    Charan|
|    PR0085456|     2026-09-24|    PL06|     MC027|     OP0561|Evening|     CTL-230|   Controllers|          777|           785|              3|              12|     275.3|         51.7|          7.75|          Pass|             Yes|    Bharat|
|    PR0082148|     2026-07-24|    PL03|     MC015|     OP0578|  Night|     VLV-320|        Valves|          431|           374|              9|               0|     78.22|        58.59|          7.67|          Pass|             Yes|     Irfan|
|    PR0053934|     2026-10-17|    PL04|     MC016|     OP0041|Evening|     CTL-230|   Controllers|         1122|           954|             21|              22|    275.02|        62.71|          7.63|          Pass|             Yes|     Gopal|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+

**8. Aggregations**

In [ ]:
from pyspark.sql.functions import sum, avg, min, max, count

1. Total units planned.

In [ ]:
df.agg(sum("units_planned").alias("total_units_planned")).show()

+-------------------+
|total_units_planned|
+-------------------+
|           87094621|
+-------------------+

2. Total units produced.

In [ ]:
df.agg(sum("units_produced").alias("total_units_produced")).show()

+--------------------+
|total_units_produced|
+--------------------+
|            80927888|
+--------------------+

3. Total defective units.

In [ ]:
df.agg(sum("defective_units").alias("total_defective_units")).show()

+---------------------+
|total_defective_units|
+---------------------+
|              2030244|
+---------------------+

4. Average units produced.

In [ ]:
df.agg(avg("units_produced").alias("average_units_produced")).show()

+----------------------+
|average_units_produced|
+----------------------+
|     674.3990666666666|
+----------------------+

5. Maximum production output.

In [ ]:
df.agg(max("units_produced").alias("maximum_units_produced")).show()

+----------------------+
|maximum_units_produced|
+----------------------+
|                  1245|
+----------------------+

6. Minimum production output.

In [ ]:
df.agg(min("units_produced").alias("minimum_units_produced")).show()

+----------------------+
|minimum_units_produced|
+----------------------+
|                   205|
+----------------------+

7. Average downtime.

In [ ]:
df.agg(avg("downtime_minutes").alias("average_downtime")).show()

+-----------------+
| average_downtime|
+-----------------+
|33.93149474428351|
+-----------------+

8. Total energy consumed.

In [ ]:
df.agg(sum("energy_kwh").alias("total_energy_consumed")).show()

+---------------------+
|total_energy_consumed|
+---------------------+
| 2.8368014080000117E7|
+---------------------+

9. Average temperature.

In [ ]:
df.agg(avg("temperature_c").alias("average_temperature")).show()

+-------------------+
|average_temperature|
+-------------------+
| 63.021532392167266|
+-------------------+

10. Average vibration.

In [ ]:
df.agg(avg("vibration_mm_s").alias("average_vibration")).show()

+-----------------+
|average_vibration|
+-----------------+
|3.398737691604917|
+-----------------+

**9. groupBy()**

Sort each summary appropriately.

In [ ]:
def summarize(keys, agg_expr, alias):
    keys = [keys] if isinstance(keys, str) else keys
    return df.groupBy(*keys).agg(agg_expr.alias(alias)).orderBy(F.col(alias).desc())

In [ ]:
from pyspark.sql import functions as F

1. Total production by plant.

In [ ]:
summarize("plant_id", F.sum("units_produced"), "total_production").show()

+--------+----------------+
|plant_id|total_production|
+--------+----------------+
|    PL03|        13547769|
|    PL02|        13546452|
|    PL04|        13529935|
|    PL06|        13492337|
|    PL01|        13488232|
|    PL05|        13323163|
+--------+----------------+

2. Total production by product family.

In [ ]:
summarize("product_family", F.sum("units_produced"), "total_production").show()

+--------------+----------------+
|product_family|total_production|
+--------------+----------------+
|        Valves|        20433082|
|         Pumps|        20208739|
|   Controllers|        20168572|
|        Motors|        20117495|
+--------------+----------------+

3. Total defects by plant.

In [ ]:
summarize("plant_id", F.sum("defective_units"), "total_defects").show()

+--------+-------------+
|plant_id|total_defects|
+--------+-------------+
|    PL01|       339720|
|    PL02|       339647|
|    PL03|       339264|
|    PL06|       338993|
|    PL04|       338118|
|    PL05|       334502|
+--------+-------------+

4. Average downtime by shift.

In [ ]:
summarize("shift", F.avg("downtime_minutes"), "average_downtime").show()

+-------+------------------+
|  shift|  average_downtime|
+-------+------------------+
|Evening|  34.2213017151833|
|  Night|33.953058820580935|
|Morning| 33.61973080530278|
+-------+------------------+

5. Average energy usage by product family.

In [ ]:
summarize("product_family", F.avg("energy_kwh"), "average_energy").show()

+--------------+------------------+
|product_family|    average_energy|
+--------------+------------------+
|        Motors|237.21818224597516|
|         Pumps|236.89137927582252|
|        Valves|236.34508750495314|
|   Controllers|235.15370433333288|
+--------------+------------------+

6. Production count by quality status.

In [ ]:
summarize("quality_status", F.count("*"), "production_count").show()

+--------------+----------------+
|quality_status|production_count|
+--------------+----------------+
|          Pass|           74328|
|        Rework|           22928|
|        Reject|           22744|
+--------------+----------------+

7. Production by plant and shift.

In [ ]:
summarize(["plant_id", "shift"], F.sum("units_produced"), "total_production").show()

+--------+-------+----------------+
|plant_id|  shift|total_production|
+--------+-------+----------------+
|    PL06|  Night|         4604432|
|    PL03|  Night|         4599608|
|    PL01|  Night|         4562612|
|    PL02|Morning|         4561068|
|    PL02|  Night|         4558467|
|    PL04|Evening|         4540617|
|    PL04|Morning|         4497099|
|    PL04|  Night|         4492219|
|    PL03|Evening|         4487211|
|    PL01|Evening|         4477769|
|    PL05|Evening|         4475101|
|    PL03|Morning|         4460950|
|    PL06|Evening|         4458798|
|    PL01|Morning|         4447851|
|    PL05|Morning|         4431446|
|    PL06|Morning|         4429107|
|    PL02|Evening|         4426917|
|    PL05|  Night|         4416616|
+--------+-------+----------------+

8. Defects by plant and product family.

In [ ]:
summarize(["plant_id", "product_family"], F.sum("defective_units"), "total_defects").show()

+--------+--------------+-------------+
|plant_id|product_family|total_defects|
+--------+--------------+-------------+
|    PL02|   Controllers|        87120|
|    PL01|         Pumps|        87103|
|    PL04|        Valves|        87084|
|    PL06|   Controllers|        86140|
|    PL06|        Valves|        85570|
|    PL03|        Valves|        85333|
|    PL03|        Motors|        84926|
|    PL01|        Valves|        84874|
|    PL03|         Pumps|        84803|
|    PL02|        Motors|        84560|
|    PL02|         Pumps|        84491|
|    PL05|        Motors|        84331|
|    PL03|   Controllers|        84202|
|    PL01|        Motors|        84174|
|    PL04|         Pumps|        83976|
|    PL04|        Motors|        83897|
|    PL06|         Pumps|        83884|
|    PL05|         Pumps|        83607|
|    PL05|   Controllers|        83589|
|    PL01|   Controllers|        83569|
+--------+--------------+-------------+
only showing top 20 rows

9. Average temperature by machine.

In [ ]:
summarize("machine_id", F.avg("temperature_c"), "average_temperature").show()

+----------+-------------------+
|machine_id|average_temperature|
+----------+-------------------+
|     MC019| 63.266223444138944|
|     MC020|  63.22489208633087|
|     MC029|  63.13119731057668|
|     MC009|   63.1252779855396|
|     MC014| 63.114309957574186|
|     MC023| 63.109051746112684|
|     MC027| 63.099668282725126|
|     MC022|  63.09403431245128|
|     MC015|  63.09026488395557|
|     MC001|   63.0778733146782|
|     MC017|  63.07674442190667|
|     MC011| 63.060230414746606|
|     MC007|    63.037661716587|
|     MC016|  63.03639870582378|
|     MC026|  63.02672521957329|
|     MC021|  63.01464069491981|
|     MC005| 62.979236446933044|
|     MC028|  62.97779683034558|
|     MC030|  62.96733774497327|
|     MC024|  62.96457946271644|
+----------+-------------------+
only showing top 20 rows

10. Total output by supervisor.

In [ ]:
summarize("supervisor", F.sum("units_produced"), "total_output").show()

+----------+------------+
|supervisor|total_output|
+----------+------------+
|     Farah|    10276986|
|    Harini|    10215803|
|     Deepa|    10130817|
|    Bharat|    10122430|
|     Anita|    10089966|
|    Charan|    10037116|
|     Gopal|    10031531|
|     Irfan|    10023239|
+----------+------------+

**10. Joining DataFrames**

In [ ]:
plant_df = spark.read.csv(
"plant_master.csv",
    header=True,
    inferSchema=True
)
plant_df.show()

+--------+---------------+---------+------+-----------+-------------+
|plant_id|     plant_name|     city|region|year_opened|plant_manager|
+--------+---------------+---------+------+-----------+-------------+
|    PL01|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|
|    PL02|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL03|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL04|    Noida Plant|    Noida| North|       2019|    M. Sharma|
|    PL05|Ahmedabad Plant|Ahmedabad|  West|       2017|     P. Desai|
|    PL06|  Kolkata Plant|  Kolkata|  East|       2020|  D. Banerjee|
+--------+---------------+---------+------+-----------+-------------+

In [ ]:
machine_df = spark.read.csv(
"machine_master.csv",
    header=True,
    inferSchema=True
)
machine_df.show()

+----------+--------+------------+-----------------+--------------+
|machine_id|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+--------+------------+-----------------+--------------+
|     MC001|    PL01|         CNC|              120|          2022|
|     MC002|    PL01|    Assembly|               80|          2024|
|     MC003|    PL01|     Casting|              120|          2018|
|     MC004|    PL01|     Welding|              180|          2024|
|     MC005|    PL01|     Testing|              150|          2022|
|     MC006|    PL02|         CNC|              100|          2021|
|     MC007|    PL02|    Assembly|              100|          2022|
|     MC008|    PL02|     Casting|              180|          2020|
|     MC009|    PL02|     Welding|               80|          2020|
|     MC010|    PL02|     Testing|              150|          2024|
|     MC011|    PL03|         CNC|              100|          2025|
|     MC012|    PL03|    Assembly|              180|          2025|
|     MC013|    PL03|     Casting|              180|          2020|
|     MC014|    PL03|     Welding|              180|          2021|
|     MC015|    PL03|     Testing|              180|          2018|
|     MC016|    PL04|         CNC|              120|          2024|
|     MC017|    PL04|    Assembly|              120|          2019|
|     MC018|    PL04|     Casting|              100|          2020|
|     MC019|    PL04|     Welding|               80|          2021|
|     MC020|    PL04|     Testing|              120|          2018|
+----------+--------+------------+-----------------+--------------+
only showing top 20 rows

1. Inner join production with plant master.

In [ ]:
inner_join_df = df.join(plant_df, on="plant_id", how="inner")
inner_join_df.show()

+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
|plant_id|production_id|production_date|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|     plant_name|     city|region|year_opened|plant_manager|
+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
|    PL03|    PR0000001|     2026-08-07|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL04|    PR0000002|     2026-08-03|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    Noida Plant|    Noida| North|       2019|    M. Sharma|
|    PL01|    PR0000003|     2026-05-20|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|
|    PL03|    PR0000004|     2026-01-15|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL04|    PR0000005|     2026-09-21|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    Noida Plant|    Noida| North|       2019|    M. Sharma|
|    PL01|    PR0000006|     2026-09-03|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|
|    PL02|    PR0000007|     2026-05-07|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL02|    PR0000008|     2026-08-17|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL03|    PR0000009|     2026-03-10|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL02|    PR0000010|     2026-02-13|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL03|    PR0000011|     2026-09-29|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL06|    PR0000012|     2026-07-10|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|  Kolkata Plant|  Kolkata|  East|       2020|  D. Banerjee|
|    PL06|    PR0000013|     2026-07-19|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|  Kolkata Plant|  Kolkata|  East|       2020|  D. Banerjee|
|    PL03|    PR0000014|     2026-05-05|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL02|    PR0000015|     2026-03-15|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|
|    PL04|    PR0000016|     2026-03-03|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    Noida Plant|    Noida| North|       2019|    M. Sharma|
|    PL03|    PR0000017|     2026-08-04|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL03|    PR0000018|     2026-01-30|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
|    PL01|    PR0000019|     2026-01-11|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|
|    PL03|    PR0000020|     2026-02-18|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|
+--------+-------------+---------------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+
only showing top 20 rows

2. Display plant name instead of only plant ID.

In [ ]:
df_with_plant_name = df.join(plant_df, on="plant_id", how="inner").select(df["*"], plant_df["plant_name"])
df_with_plant_name.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|     plant_name|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|  Chennai Plant|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    Noida Plant|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|Hyderabad Plant|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|  Chennai Plant|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    Noida Plant|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|Hyderabad Plant|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|     Pune Plant|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|     Pune Plant|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|  Chennai Plant|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|     Pune Plant|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|  Chennai Plant|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|  Kolkata Plant|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|  Kolkata Plant|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|  Chennai Plant|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|     Pune Plant|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    Noida Plant|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|  Chennai Plant|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|  Chennai Plant|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|Hyderabad Plant|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|  Chennai Plant|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
only showing top 20 rows

3. Join production with machine master.

In [ ]:
production_with_machine_master = df.join(machine_df, on="machine_id", how="inner")
production_with_machine_master.show()

+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|     MC011|    PR0000001|     2026-08-07|    PL03|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|    PL03|         CNC|              100|          2025|
|     MC019|    PR0000002|     2026-08-03|    PL04|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    PL04|     Welding|               80|          2021|
|     MC002|    PR0000003|     2026-05-20|    PL01|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|    PL01|    Assembly|               80|          2024|
|     MC013|    PR0000004|     2026-01-15|    PL03|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|    PL03|     Casting|              180|          2020|
|     MC020|    PR0000005|     2026-09-21|    PL04|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    PL04|     Testing|              120|          2018|
|     MC002|    PR0000006|     2026-09-03|    PL01|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|    PL01|    Assembly|               80|          2024|
|     MC007|    PR0000007|     2026-05-07|    PL02|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|    PL02|    Assembly|              100|          2022|
|     MC009|    PR0000008|     2026-08-17|    PL02|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|    PL02|     Welding|               80|          2020|
|     MC015|    PR0000009|     2026-03-10|    PL03|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    PL03|     Testing|              180|          2018|
|     MC006|    PR0000010|     2026-02-13|    PL02|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|    PL02|         CNC|              100|          2021|
|     MC012|    PR0000011|     2026-09-29|    PL03|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|    PL03|    Assembly|              180|          2025|
|     MC030|    PR0000012|     2026-07-10|    PL06|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|    PL06|     Testing|              150|          2021|
|     MC027|    PR0000013|     2026-07-19|    PL06|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    PL06|    Assembly|              150|          2020|
|     MC013|    PR0000014|     2026-05-05|    PL03|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|    PL03|     Casting|              180|          2020|
|     MC007|    PR0000015|     2026-03-15|    PL02|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|    PL02|    Assembly|              100|          2022|
|     MC020|    PR0000016|     2026-03-03|    PL04|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    PL04|     Testing|              120|          2018|
|     MC011|    PR0000017|     2026-08-04|    PL03|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|    PL03|         CNC|              100|          2025|
|     MC012|    PR0000018|     2026-01-30|    PL03|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|    PL03|    Assembly|              180|          2025|
|     MC005|    PR0000019|     2026-01-11|    PL01|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|    PL01|     Testing|              150|          2022|
|     MC014|    PR0000020|     2026-02-18|    PL03|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|    PL03|     Welding|              180|          2021|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
only showing top 20 rows

4. Create one DataFrame containing production + plant + machine information.

In [ ]:
full_df = df.join(plant_df, on="plant_id", how="inner").join(machine_df, on="machine_id", how="inner")
full_df.show()

+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+--------+------------+-----------------+--------------+
|machine_id|plant_id|production_id|production_date|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|     plant_name|     city|region|year_opened|plant_manager|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+--------+------------+-----------------+--------------+
|     MC011|    PL03|    PR0000001|     2026-08-07|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|         CNC|              100|          2025|
|     MC019|    PL04|    PR0000002|     2026-08-03|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    Noida Plant|    Noida| North|       2019|    M. Sharma|    PL04|     Welding|               80|          2021|
|     MC002|    PL01|    PR0000003|     2026-05-20|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|    PL01|    Assembly|               80|          2024|
|     MC013|    PL03|    PR0000004|     2026-01-15|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|     Casting|              180|          2020|
|     MC020|    PL04|    PR0000005|     2026-09-21|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    Noida Plant|    Noida| North|       2019|    M. Sharma|    PL04|     Testing|              120|          2018|
|     MC002|    PL01|    PR0000006|     2026-09-03|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|    PL01|    Assembly|               80|          2024|
|     MC007|    PL02|    PR0000007|     2026-05-07|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|    PL02|    Assembly|              100|          2022|
|     MC009|    PL02|    PR0000008|     2026-08-17|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|    PL02|     Welding|               80|          2020|
|     MC015|    PL03|    PR0000009|     2026-03-10|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|     Testing|              180|          2018|
|     MC006|    PL02|    PR0000010|     2026-02-13|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|    PL02|         CNC|              100|          2021|
|     MC012|    PL03|    PR0000011|     2026-09-29|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|    Assembly|              180|          2025|
|     MC030|    PL06|    PR0000012|     2026-07-10|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|  Kolkata Plant|  Kolkata|  East|       2020|  D. Banerjee|    PL06|     Testing|              150|          2021|
|     MC027|    PL06|    PR0000013|     2026-07-19|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|  Kolkata Plant|  Kolkata|  East|       2020|  D. Banerjee|    PL06|    Assembly|              150|          2020|
|     MC013|    PL03|    PR0000014|     2026-05-05|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|     Casting|              180|          2020|
|     MC007|    PL02|    PR0000015|     2026-03-15|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|    PL02|    Assembly|              100|          2022|
|     MC020|    PL04|    PR0000016|     2026-03-03|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    Noida Plant|    Noida| North|       2019|    M. Sharma|    PL04|     Testing|              120|          2018|
|     MC011|    PL03|    PR0000017|     2026-08-04|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|         CNC|              100|          2025|
|     MC012|    PL03|    PR0000018|     2026-01-30|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|    Assembly|              180|          2025|
|     MC005|    PL01|    PR0000019|     2026-01-11|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|    PL01|     Testing|              150|          2022|
|     MC014|    PL03|    PR0000020|     2026-02-18|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|    PL03|     Welding|              180|          2021|
+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+--------+------------+-----------------+--------------+
only showing top 20 rows

5. Calculate total production by plant city.

In [ ]:
full_df.groupBy("city").agg(sum("units_produced").alias("total_production")).show()

+---------+----------------+
|     city|total_production|
+---------+----------------+
|  Chennai|        13547769|
|Ahmedabad|        13323163|
|  Kolkata|        13492337|
|    Noida|        13529935|
|     Pune|        13546452|
|Hyderabad|        13488232|
+---------+----------------+

6. Calculate average downtime by machine type.

In [ ]:
full_df.groupBy("machine_type").agg(avg("downtime_minutes").alias("average_downtime")).show()

+------------+-----------------+
|machine_type| average_downtime|
+------------+-----------------+
|         CNC|33.64548129466162|
|     Testing|33.87585594724829|
|     Welding|34.00449382099613|
|    Assembly|33.96718284443325|
|     Casting| 34.1660783396419|
+------------+-----------------+

7. Calculate defects by region.

In [ ]:
full_df.groupBy("region").agg(sum("defective_units").alias("total_defects")).show()

+------+-------------+
|region|total_defects|
+------+-------------+
| South|       678984|
|  East|       338993|
|  West|       674149|
| North|       338118|
+------+-------------+

8. Find production records without matching machine master records.

In [ ]:
df.join(machine_df, on="machine_id", how="left_anti").show()

+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|machine_id|production_id|production_date|plant_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+

9. Perform a left join and inspect unmatched records.

In [ ]:
left_join_df = df.join(machine_df, on="machine_id", how="left")
left_join_df.filter(left_join_df["machine_id"].isNull()).show()

+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|plant_id|machine_type|capacity_per_hour|installed_year|
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+
+----------+-------------+---------------+--------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+--------+------------+-----------------+--------------+

10. Find total energy consumption by plant name.

In [ ]:
full_df.groupBy("plant_name").agg(sum("energy_kwh").alias("total_energy_consumption")).show()

+---------------+------------------------+
|     plant_name|total_energy_consumption|
+---------------+------------------------+
|    Noida Plant|       4746238.580000002|
|  Kolkata Plant|       4723180.160000009|
|  Chennai Plant|       4742748.169999995|
|     Pune Plant|       4757984.949999988|
|Hyderabad Plant|       4725471.189999996|
|Ahmedabad Plant|        4672391.03000001|
+---------------+------------------------+

**11. Updating Data**

1. Change Reject to Failed.

In [ ]:
df2 = df2.withColumn("quality_status", F.when(df2["quality_status"] == "Reject", "Failed").otherwise(df2["quality_status"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|         993.0|             30|              34|         388.11|         61.4|          3.88|        Rework|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|         836.0|              0|               0|         398.58|        64.37|          2.28|        Failed|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|         380.0|             17|              15|         183.34|        54.13|          4.66|        Failed|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|         720.0|              7|              39|         217.61|        64.47|          NULL|        Rework|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|         296.0|              7|              49|         115.47|        72.59|          3.21|          Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|         795.0|             50|              44|         290.26|        64.91|          2.77|        Rework|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|         955.0|             10|               5|         355.56|        62.76|          2.89|          Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|         895.0|             51|              77|         266.06|         57.1|          1.34|        Failed|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|         289.0|              8|              16|          87.62|        66.55|          3.07|          Pass|             Yes|     Anita|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|         527.0|             26|              64|         112.17|        60.96|          3.48|        Failed|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|         512.0|             14|              32|          127.0|        52.81|          3.46|          Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|         968.0|             23|              38|         377.97|        69.79|          3.43|        Rework|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|         867.0|             27|              66|         388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|         456.0|              6|               6|         108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|        1042.0|              4|             172|         239.64|        76.39|          2.81|          Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|         732.0|              0|              13|         289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|         963.0|             28|              91|         347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|         469.0|             18|              36|         241.05|        59.91|          3.87|          Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|         380.0|             16|              25|         137.99|        62.23|          4.29|          Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|         573.0|             13|              64|         277.73|        76.92|          2.35|          Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+--------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
only showing top 20 rows

2. Change Rework to Requires Review.

In [ ]:
df2 = df2.withColumn("quality_status", F.when(df2["quality_status"] == "Rework", "Requires Review").otherwise(df2["quality_status"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|         895.0|             51|              77|         266.06|         57.1|          1.34|         Failed|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes|     Anita|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|         512.0|             14|              32|          127.0|        52.81|          3.46|           Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|         867.0|             27|              66|         388.61|        50.88|           5.7|           Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
only showing top 20 rows

3. Increase units planned by 5% for Motors.

In [ ]:
df2 = df2.withColumn("units_planned", F.when(df2["product_family"] == "Motors", df2["units_planned"] * 1.05).otherwise(df2["units_planned"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|             862.0|         895.0|             51|              77|         266.06|         57.1|          1.34|         Failed|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes|     Anita|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|             577.0|         512.0|             14|              32|          127.0|        52.81|          3.46|           Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|            1004.0|         867.0|             27|              66|         388.61|        50.88|           5.7|           Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
only showing top 20 rows

4. Increase energy consumption by 3% for Night shifts.

In [ ]:
df2 = df2.withColumn("energy_consumed", F.when(df2["shift"] == "Night", df2["energy_consumed"] * 1.03).otherwise(df2["energy_consumed"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes|     Anita|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
only showing top 20 rows

5. Replace missing operator IDs with UNASSIGNED.

In [ ]:
df2 = df2.withColumn("operator_id", F.when(df2["operator_id"].isNull(), "UNASSIGNED").otherwise(df2["operator_id"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes|     Anita|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
only showing top 20 rows

6. Replace supervisor Anita with Anita Rao.

In [ ]:
df2 = df2.withColumn("supervisor", F.when(df2["supervisor"] == "Anita", "Anita Rao").otherwise(df2["supervisor"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| Anita Rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+
only showing top 20 rows

7. Create a corrected temperature column.

In [ ]:
df2 = df2.withColumn("corrected_temperature", F.when(df2["temperature_c"] > 100, 100).otherwise(df2["temperature_c"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| Anita Rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
only showing top 20 rows

**12. Null Values and na Functions**

In [ ]:
before = df.count()

1. Count missing operator IDs.

In [ ]:
df.filter(df["operator_id"].isNull()).count()

1524

2. Count missing temperature values.

In [ ]:
df.filter(df["temperature_c"].isNull()).count()

2132

3. Count missing vibration values.

In [ ]:
df.filter(df["vibration_mm_s"].isNull()).count()

1788

4. Count missing downtime.

In [ ]:
df.filter(df["downtime_minutes"].isNull()).count()

1177

5. Use na.drop()

In [ ]:
df.na.drop(subset=["operator_id"]).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

6. Drop only rows where temperature is missing.

In [ ]:
df.na.drop(subset=["temperature_c"]).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

7. Fill missing downtime with 0.

In [ ]:
df.na.fill({"downtime_minutes": 0}).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

8. Fill missing operator ID with UNKNOWN.

In [ ]:
df.na.fill({"operator_id": "UNKNOWN"}).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

9. Fill missing temperature with the overall average temperature.

In [ ]:
average_temperature = df.agg(F.avg("temperature_c")).first()[0]
df.na.fill({"temperature_c": average_temperature}).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

10. Compare record counts before and after cleansing.

In [ ]:
print("Before cleansing:", before)
print("After cleansing:", df.count())

Before cleansing: 120000
After cleansing: 120000

**13. Built-in Functions**

1. Convert product family to uppercase.

In [ ]:
df2 = df2.withColumn("product_family", F.upper(df2["product_family"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    Charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     Farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     Deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     Farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     Deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     Gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     Gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     Irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| Anita Rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     Gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    Bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     Gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     Deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     Deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     Deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     Irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     Gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     Farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     Deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     Irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
only showing top 20 rows

2. Convert supervisor names to lowercase.

In [ ]:
df2 = df2.withColumn("supervisor", F.lower(df2["supervisor"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
only showing top 20 rows

3. Trim operator IDs.

In [ ]:
df2 = df2.withColumn("operator_id", F.trim(df2["operator_id"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+
only showing top 20 rows

4. Find length of product codes.

In [ ]:
df2 = df2.withColumn("product_code_length", F.length(df2["product_code"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|product_code_length|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|                  7|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|                  7|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|                  7|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|                  7|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|                  7|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|                  7|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|                  7|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|                  7|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|                  7|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|                  7|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|                  7|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|                  7|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|                  7|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|                  7|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|                  7|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|                  7|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|                  7|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|                  7|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|                  7|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|                  7|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+
only showing top 20 rows

5. Combine plant ID and machine ID.

In [ ]:
df2 = df2.withColumn("plant_machine_id", F.concat(df2["plant_id"], F.lit("-"), df2["machine_id"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|product_code_length|plant_machine_id|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|                  7|      PL03-MC011|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|                  7|      PL04-MC019|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|                  7|      PL01-MC002|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|                  7|      PL03-MC013|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|                  7|      PL04-MC020|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|                  7|      PL01-MC002|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|                  7|      PL02-MC007|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|                  7|      PL02-MC009|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|                  7|      PL03-MC015|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|                  7|      PL02-MC006|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|                  7|      PL03-MC012|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|                  7|      PL06-MC030|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|                  7|      PL06-MC027|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|                  7|      PL03-MC013|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|                  7|      PL02-MC007|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|                  7|      PL04-MC020|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|                  7|      PL03-MC011|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|                  7|      PL03-MC012|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|                  7|      PL01-MC005|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|                  7|      PL03-MC014|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+
only showing top 20 rows

6. Round temperature to one decimal.

In [ ]:
df2 = df2.withColumn("rounded_temperature", F.round(df2["temperature_c"], 1))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|product_code_length|plant_machine_id|rounded_temperature|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|                  7|      PL03-MC011|               61.4|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|                  7|      PL04-MC019|               64.4|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|                  7|      PL01-MC002|               54.1|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|                  7|      PL03-MC013|               64.5|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|                  7|      PL04-MC020|               72.6|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|                  7|      PL01-MC002|               64.9|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|                  7|      PL02-MC007|               62.8|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|                  7|      PL02-MC009|               57.1|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|                  7|      PL03-MC015|               66.6|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|                  7|      PL02-MC006|               61.0|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|                  7|      PL03-MC012|               52.8|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|                  7|      PL06-MC030|               69.8|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|                  7|      PL06-MC027|               50.9|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|                  7|      PL03-MC013|               67.2|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|                  7|      PL02-MC007|               76.4|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|                  7|      PL04-MC020|               44.9|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|                  7|      PL03-MC011|               75.1|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|                  7|      PL03-MC012|               59.9|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|                  7|      PL01-MC005|               62.2|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|                  7|      PL03-MC014|               76.9|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+
only showing top 20 rows

7. Calculate absolute difference between planned and produced units.

In [ ]:
df2 = df2.withColumn("unit_difference", F.abs(df2["units_planned"] - df2["units_produced"]))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|product_code_length|plant_machine_id|rounded_temperature|  unit_difference|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|                  7|      PL03-MC011|               61.4|            120.0|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|                  7|      PL04-MC019|               64.4|             27.0|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|                  7|      PL01-MC002|               54.1|84.10000000000002|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|                  7|      PL03-MC013|               64.5|             67.0|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|                  7|      PL04-MC020|               72.6|             48.0|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|                  7|      PL01-MC002|               64.9|210.9000000000001|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|                  7|      PL02-MC007|               62.8|            210.0|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|                  7|      PL02-MC009|               57.1|             33.0|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|                  7|      PL03-MC015|               66.6|             24.0|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|                  7|      PL02-MC006|               61.0|              5.0|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|                  7|      PL03-MC012|               52.8|             65.0|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|                  7|      PL06-MC030|               69.8|             12.0|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|                  7|      PL06-MC027|               50.9|            137.0|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|                  7|      PL03-MC013|               67.2|              8.0|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|                  7|      PL02-MC007|               76.4|98.29999999999995|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|                  7|      PL04-MC020|               44.9|            138.0|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|                  7|      PL03-MC011|               75.1|            189.0|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|                  7|      PL03-MC012|               59.9|99.05000000000007|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|                  7|      PL01-MC005|               62.2|              1.0|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|                  7|      PL03-MC014|               76.9|             73.0|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+
only showing top 20 rows

8. Replace characters in production ID using regexp_replace.

In [ ]:
df2 = df2.withColumn("production_id", F.regexp_replace(df2["production_id"], "-", ""))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|product_code_length|plant_machine_id|rounded_temperature|  unit_difference|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|                  7|      PL03-MC011|               61.4|            120.0|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|                  7|      PL04-MC019|               64.4|             27.0|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|                  7|      PL01-MC002|               54.1|84.10000000000002|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|                  7|      PL03-MC013|               64.5|             67.0|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|                  7|      PL04-MC020|               72.6|             48.0|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|                  7|      PL01-MC002|               64.9|210.9000000000001|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|                  7|      PL02-MC007|               62.8|            210.0|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|                  7|      PL02-MC009|               57.1|             33.0|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|                  7|      PL03-MC015|               66.6|             24.0|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|                  7|      PL02-MC006|               61.0|              5.0|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|                  7|      PL03-MC012|               52.8|             65.0|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|                  7|      PL06-MC030|               69.8|             12.0|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|                  7|      PL06-MC027|               50.9|            137.0|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|                  7|      PL03-MC013|               67.2|              8.0|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|                  7|      PL02-MC007|               76.4|98.29999999999995|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|                  7|      PL04-MC020|               44.9|            138.0|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|                  7|      PL03-MC011|               75.1|            189.0|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|                  7|      PL03-MC012|               59.9|99.05000000000007|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|                  7|      PL01-MC005|               62.2|              1.0|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|                  7|      PL03-MC014|               76.9|             73.0|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+
only showing top 20 rows

9. Extract part of product code using substring.

In [ ]:
df2 = df2.withColumn("product_code_part", F.substring(df2["product_code"], 1, 3))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+-----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|product_code_length|plant_machine_id|rounded_temperature|  unit_difference|product_code_part|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+-----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|                  7|      PL03-MC011|               61.4|            120.0|              MTR|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|                  7|      PL04-MC019|               64.4|             27.0|              CTL|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|                  7|      PL01-MC002|               54.1|84.10000000000002|              MTR|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|                  7|      PL03-MC013|               64.5|             67.0|              PMP|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|                  7|      PL04-MC020|               72.6|             48.0|              PMP|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|                  7|      PL01-MC002|               64.9|210.9000000000001|              MTR|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|                  7|      PL02-MC007|               62.8|            210.0|              VLV|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|                  7|      PL02-MC009|               57.1|             33.0|              VLV|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|                  7|      PL03-MC015|               66.6|             24.0|              CTL|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|                  7|      PL02-MC006|               61.0|              5.0|              CTL|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|                  7|      PL03-MC012|               52.8|             65.0|              PMP|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|                  7|      PL06-MC030|               69.8|             12.0|              CTL|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|                  7|      PL06-MC027|               50.9|            137.0|              CTL|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|                  7|      PL03-MC013|               67.2|              8.0|              VLV|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|                  7|      PL02-MC007|               76.4|98.29999999999995|              MTR|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|                  7|      PL04-MC020|               44.9|            138.0|              CTL|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|                  7|      PL03-MC011|               75.1|            189.0|              CTL|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|                  7|      PL03-MC012|               59.9|99.05000000000007|              MTR|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|                  7|      PL01-MC005|               62.2|              1.0|              VLV|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|                  7|      PL03-MC014|               76.9|             73.0|              PMP|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+-----------------+
only showing top 20 rows

10. Use coalesce() to return temperature or a default value.

In [ ]:
df2 = df2.withColumn("corrected_temperature", F.coalesce(df2["temperature_c"], F.lit(25.0)))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+-----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_consumed|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|production_efficiency|good_units|country| defect_percentage|    energy_per_unit|corrected_temperature|product_code_length|plant_machine_id|rounded_temperature|  unit_difference|product_code_part|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+-----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        MOTORS|            1113.0|         993.0|             30|              34|         388.11|         61.4|          3.88|Requires Review|              No|    charan|    93.67924528301886|       963|  India|3.0211480362537766|0.39084592145015107|                 61.4|                  7|      PL03-MC011|               61.4|            120.0|              MTR|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   CONTROLLERS|             809.0|         836.0|              0|               0|         398.58|        64.37|          2.28|         Failed|              No|     farah|   103.33745364647713|       836|  India|               0.0| 0.4767703349282296|                64.37|                  7|      PL04-MC019|               64.4|             27.0|              CTL|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        MOTORS|             464.1|         380.0|             17|              15|         183.34|        54.13|          4.66|         Failed|              No|     deepa|    85.97285067873304|       363|  India| 4.473684210526316|0.48247368421052633|                54.13|                  7|      PL01-MC002|               54.1|84.10000000000002|              MTR|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         PUMPS|             787.0|         720.0|              7|              39|         217.61|        64.47|          NULL|Requires Review|              No|     farah|     91.4866581956798|       713|  India|0.9722222222222222|0.30223611111111115|                64.47|                  7|      PL03-MC013|               64.5|             67.0|              PMP|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         PUMPS|             344.0|         296.0|              7|              49|         115.47|        72.59|          3.21|           Pass|              No|     deepa|    86.04651162790698|       289|  India| 2.364864864864865| 0.3901013513513513|                72.59|                  7|      PL04-MC020|               72.6|             48.0|              PMP|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        MOTORS|1005.9000000000001|         795.0|             50|              44|         290.26|        64.91|          2.77|Requires Review|              No|     gopal|    82.98538622129436|       745|  India| 6.289308176100629| 0.3651069182389937|                64.91|                  7|      PL01-MC002|               64.9|210.9000000000001|              MTR|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        VALVES|            1165.0|         955.0|             10|               5|         355.56|        62.76|          2.89|           Pass|              No|     gopal|    81.97424892703863|       945|  India|1.0471204188481675|0.37231413612565445|                62.76|                  7|      PL02-MC007|               62.8|            210.0|              VLV|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        VALVES|             862.0|         895.0|             51|              77|       274.0418|         57.1|          1.34|         Failed|              No|     irfan|   103.82830626450117|       844|  India| 5.698324022346369| 0.2972737430167598|                 57.1|                  7|      PL02-MC009|               57.1|             33.0|              VLV|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   CONTROLLERS|             313.0|         289.0|              8|              16|          87.62|        66.55|          3.07|           Pass|             Yes| anita rao|    92.33226837060703|       281|  India| 2.768166089965398| 0.3031833910034602|                66.55|                  7|      PL03-MC015|               66.6|             24.0|              CTL|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   CONTROLLERS|             532.0|         527.0|             26|              64|         112.17|        60.96|          3.48|         Failed|              No|     gopal|    99.06015037593986|       501|  India| 4.933586337760911| 0.2128462998102467|                60.96|                  7|      PL02-MC006|               61.0|              5.0|              CTL|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         PUMPS|             577.0|         512.0|             14|              32|         130.81|        52.81|          3.46|           Pass|              No|    bharat|    88.73483535528595|       498|  India|          2.734375|        0.248046875|                52.81|                  7|      PL03-MC012|               52.8|             65.0|              PMP|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   CONTROLLERS|             980.0|         968.0|             23|              38|         377.97|        69.79|          3.43|Requires Review|              No|     gopal|    98.77551020408163|       945|  India|  2.37603305785124| 0.3904648760330579|                69.79|                  7|      PL06-MC030|               69.8|             12.0|              CTL|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   CONTROLLERS|            1004.0|         867.0|             27|              66|       400.2683|        50.88|           5.7|           Pass|             Yes|     deepa|    86.35458167330677|       840|  India|3.1141868512110724| 0.4482237600922722|                50.88|                  7|      PL06-MC027|               50.9|            137.0|              CTL|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        VALVES|             448.0|         456.0|              6|               6|         108.83|         67.2|          3.12|           Pass|             Yes|     deepa|   101.78571428571428|       450|  India|1.3157894736842104|0.23866228070175438|                 67.2|                  7|      PL03-MC013|               67.2|              8.0|              VLV|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        MOTORS|            1140.3|        1042.0|              4|             172|         239.64|        76.39|          2.81|           Pass|              No|     deepa|    95.94843462246777|      1038|  India|0.3838771593090211|0.22998080614203453|                76.39|                  7|      PL02-MC007|               76.4|98.29999999999995|              MTR|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   CONTROLLERS|             870.0|         732.0|              0|              13|         289.55|        44.92|          4.81|           Pass|             Yes|     irfan|    84.13793103448276|       732|  India|               0.0| 0.3955601092896175|                44.92|                  7|      PL04-MC020|               44.9|            138.0|              CTL|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   CONTROLLERS|            1152.0|         963.0|             28|              91|         347.34|        75.09|           4.0|           Pass|             Yes|     gopal|             83.59375|       935|  India| 2.907580477673936|0.36068535825545167|                75.09|                  7|      PL03-MC011|               75.1|            189.0|              CTL|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        MOTORS| 568.0500000000001|         469.0|             18|              36|         241.05|        59.91|          3.87|           Pass|              No|     farah|    86.69131238447319|       451|  India|3.8379530916844353| 0.5139658848614073|                59.91|                  7|      PL03-MC012|               59.9|99.05000000000007|              MTR|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        VALVES|             381.0|         380.0|             16|              25|         137.99|        62.23|          4.29|           Pass|              No|     deepa|    99.73753280839895|       364|  India|4.2105263157894735|0.36313157894736847|                62.23|                  7|      PL01-MC005|               62.2|              1.0|              VLV|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         PUMPS|             646.0|         573.0|             13|              64|         277.73|        76.92|          2.35|           Pass|              No|     irfan|    88.69969040247679|       560|  India|2.2687609075043627|  0.484694589877836|                76.92|                  7|      PL03-MC014|               76.9|             73.0|              PMP|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+---------------+-------------+--------------+---------------+----------------+----------+---------------------+----------+-------+------------------+-------------------+---------------------+-------------------+----------------+-------------------+-----------------+-----------------+
only showing top 20 rows

**14. when() / otherwise()**

Create:

**Efficiency Category**

gt= 100%  → Above Target
gt= 95%   → On Target
gt= 85%   → Below Target
otherwise → Critical

**Defect Category**

0               → Perfect
1–10            → Normal
11–25           → Attention
above 25        → High Defect

**Machine Condition**

Use temperature and vibration:
High temperature OR high vibration → Inspect
otherwise                          → Normal

Then count records in each resulting category.

In [ ]:
from pyspark.sql import functions as F

# Calculate production efficiency if not already present
df_categorized = df.withColumn(
    "production_efficiency",
    (F.col("units_produced") / F.col("units_planned")) * 100
)

# 1. Create Efficiency Category
df_categorized = df_categorized.withColumn(
    "efficiency_category",
    F.when(F.col("production_efficiency") >= 100, "Above Target")
     .when(F.col("production_efficiency") >= 95, "On Target")
     .when(F.col("production_efficiency") >= 85, "Below Target")
     .otherwise("Critical")
)

# 2. Create Defect Category
df_categorized = df_categorized.withColumn(
    "defect_category",
    F.when(F.col("defective_units") == 0, "Perfect")
     .when(F.col("defective_units") <= 10, "Normal")
     .when(F.col("defective_units") <= 25, "Attention")
     .otherwise("High Defect")
)

# 3. Create Machine Condition Category
# Use overall averages as reference for threshold if desired, or define specific thresholds.
# Here we define high temperature as > 75 (reference to earlier cells) or vibration > 4.5.
# Adjusting thresholds safely to make sure both conditions function properly.
temp_threshold = 75.0
vib_threshold = 4.5

df_categorized = df_categorized.withColumn(
    "machine_condition",
    F.when(
        (F.col("temperature_c") > temp_threshold) | (F.col("vibration_mm_s") > vib_threshold),
        "Inspect"
    ).otherwise("Normal")
)

# Display some sample output with the new categories
df_categorized.select(
    "production_id",
    "production_efficiency",
    "efficiency_category",
    "defective_units",
    "defect_category",
    "temperature_c",
    "vibration_mm_s",
    "machine_condition"
).show(10)

# Count records in each category
print("=== Efficiency Category Counts ===")
df_categorized.groupBy("efficiency_category").count().show()

print("=== Defect Category Counts ===")
df_categorized.groupBy("defect_category").count().show()

print("=== Machine Condition Counts ===")
df_categorized.groupBy("machine_condition").count().show()

+-------------+---------------------+-------------------+---------------+---------------+-------------+--------------+-----------------+
|production_id|production_efficiency|efficiency_category|defective_units|defect_category|temperature_c|vibration_mm_s|machine_condition|
+-------------+---------------------+-------------------+---------------+---------------+-------------+--------------+-----------------+
|    PR0000001|    93.67924528301886|       Below Target|             30|    High Defect|         61.4|          3.88|           Normal|
|    PR0000002|   103.33745364647713|       Above Target|              0|        Perfect|        64.37|          2.28|           Normal|
|    PR0000003|    85.97285067873304|       Below Target|             17|      Attention|        54.13|          4.66|          Inspect|
|    PR0000004|     91.4866581956798|       Below Target|              7|         Normal|        64.47|          NULL|           Normal|
|    PR0000005|    86.04651162790698|       Below Target|              7|         Normal|        72.59|          3.21|           Normal|
|    PR0000006|    82.98538622129436|           Critical|             50|    High Defect|        64.91|          2.77|           Normal|
|    PR0000007|    81.97424892703863|           Critical|             10|         Normal|        62.76|          2.89|           Normal|
|    PR0000008|   103.82830626450117|       Above Target|             51|    High Defect|         57.1|          1.34|           Normal|
|    PR0000009|    92.33226837060703|       Below Target|              8|         Normal|        66.55|          3.07|           Normal|
|    PR0000010|    99.06015037593986|          On Target|             26|    High Defect|        60.96|          3.48|           Normal|
+-------------+---------------------+-------------------+---------------+---------------+-------------+--------------+-----------------+
only showing top 10 rows
=== Efficiency Category Counts ===
+-------------------+-----+
|efficiency_category|count|
+-------------------+-----+
|       Above Target|21735|
|          On Target|26825|
|       Below Target|54619|
|           Critical|16821|
+-------------------+-----+

=== Defect Category Counts ===
+---------------+-----+
|defect_category|count|
+---------------+-----+
|      Attention|45745|
|        Perfect|11491|
|    High Defect|28058|
|         Normal|34706|
+---------------+-----+

=== Machine Condition Counts ===
+-----------------+-----+
|machine_condition|count|
+-----------------+-----+
|          Inspect|25163|
|           Normal|94837|
+-----------------+-----+

**15. Complex JSON**

In [ ]:
machine_json = spark.read.option(
"multiline", "true"
).json("machine_configurations.json")

1. Display schema.

In [ ]:
machine_json.printSchema()

root
 |-- capacity_per_hour: long (nullable = true)
 |-- installed_year: long (nullable = true)
 |-- machine_id: string (nullable = true)
 |-- machine_type: string (nullable = true)
 |-- maintenance: struct (nullable = true)
 |    |-- frequency_days: long (nullable = true)
 |    |-- last_service: string (nullable = true)
 |-- plant_id: string (nullable = true)
 |-- sensors: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- active: boolean (nullable = true)
 |    |    |-- sensor: string (nullable = true)
 |    |    |-- unit: string (nullable = true)
 |-- specifications: struct (nullable = true)
 |    |-- max_temperature_c: long (nullable = true)
 |    |-- rated_power_kw: long (nullable = true)
 |    |-- vibration_limit_mm_s: double (nullable = true)

2. Display machine ID and machine type.

In [ ]:
machine_json.select("machine_id", "machine_type").show()

+----------+------------+
|machine_id|machine_type|
+----------+------------+
|     MC001|         CNC|
|     MC002|    Assembly|
|     MC003|     Casting|
|     MC004|     Welding|
|     MC005|     Testing|
|     MC006|         CNC|
|     MC007|    Assembly|
|     MC008|     Casting|
|     MC009|     Welding|
|     MC010|     Testing|
|     MC011|         CNC|
|     MC012|    Assembly|
|     MC013|     Casting|
|     MC014|     Welding|
|     MC015|     Testing|
|     MC016|         CNC|
|     MC017|    Assembly|
|     MC018|     Casting|
|     MC019|     Welding|
|     MC020|     Testing|
+----------+------------+
only showing top 20 rows

3. Extract specifications.rated_power_kw.

In [ ]:
machine_json.select("machine_id", "specifications.rated_power_kw").show()

+----------+--------------+
|machine_id|rated_power_kw|
+----------+--------------+
|     MC001|            22|
|     MC002|            22|
|     MC003|            55|
|     MC004|            22|
|     MC005|            30|
|     MC006|            30|
|     MC007|            22|
|     MC008|            55|
|     MC009|            30|
|     MC010|            55|
|     MC011|            30|
|     MC012|            55|
|     MC013|            30|
|     MC014|            30|
|     MC015|            45|
|     MC016|            30|
|     MC017|            30|
|     MC018|            30|
|     MC019|            30|
|     MC020|            15|
+----------+--------------+
only showing top 20 rows

4. Extract maximum temperature.

In [ ]:
machine_json.select("machine_id", "specifications.max_temperature_c").show()

+----------+-----------------+
|machine_id|max_temperature_c|
+----------+-----------------+
|     MC001|               85|
|     MC002|               85|
|     MC003|               90|
|     MC004|               85|
|     MC005|               85|
|     MC006|               85|
|     MC007|               80|
|     MC008|               75|
|     MC009|               85|
|     MC010|               90|
|     MC011|               90|
|     MC012|               80|
|     MC013|               90|
|     MC014|               80|
|     MC015|               90|
|     MC016|               75|
|     MC017|               85|
|     MC018|               85|
|     MC019|               75|
|     MC020|               80|
+----------+-----------------+
only showing top 20 rows

5. Extract vibration limit.

In [ ]:
machine_json.select("machine_id", "specifications.vibration_limit_mm_s").show()

+----------+--------------------+
|machine_id|vibration_limit_mm_s|
+----------+--------------------+
|     MC001|                 5.0|
|     MC002|                 5.5|
|     MC003|                 4.5|
|     MC004|                 4.5|
|     MC005|                 4.5|
|     MC006|                 5.5|
|     MC007|                 4.5|
|     MC008|                 5.0|
|     MC009|                 5.5|
|     MC010|                 4.5|
|     MC011|                 6.0|
|     MC012|                 5.5|
|     MC013|                 5.0|
|     MC014|                 5.5|
|     MC015|                 4.5|
|     MC016|                 5.5|
|     MC017|                 4.5|
|     MC018|                 5.0|
|     MC019|                 5.0|
|     MC020|                 5.0|
+----------+--------------------+
only showing top 20 rows

6. Display maintenance frequency.

In [ ]:
machine_json.select("machine_id", "maintenance.frequency_days").show()

+----------+--------------+
|machine_id|frequency_days|
+----------+--------------+
|     MC001|            60|
|     MC002|            60|
|     MC003|            45|
|     MC004|            60|
|     MC005|            30|
|     MC006|            60|
|     MC007|            30|
|     MC008|            30|
|     MC009|            30|
|     MC010|            45|
|     MC011|            30|
|     MC012|            30|
|     MC013|            60|
|     MC014|            90|
|     MC015|            30|
|     MC016|            45|
|     MC017|            30|
|     MC018|            30|
|     MC019|            30|
|     MC020|            45|
+----------+--------------+
only showing top 20 rows

7. Work with the sensors array.

In [ ]:
machine_json.select("machine_id", "sensors").show()

+----------+--------------------+
|machine_id|             sensors|
+----------+--------------------+
|     MC001|[{true, temperatu...|
|     MC002|[{true, temperatu...|
|     MC003|[{true, temperatu...|
|     MC004|[{true, temperatu...|
|     MC005|[{true, temperatu...|
|     MC006|[{true, temperatu...|
|     MC007|[{true, temperatu...|
|     MC008|[{true, temperatu...|
|     MC009|[{true, temperatu...|
|     MC010|[{true, temperatu...|
|     MC011|[{true, temperatu...|
|     MC012|[{true, temperatu...|
|     MC013|[{true, temperatu...|
|     MC014|[{true, temperatu...|
|     MC015|[{true, temperatu...|
|     MC016|[{true, temperatu...|
|     MC017|[{true, temperatu...|
|     MC018|[{true, temperatu...|
|     MC019|[{true, temperatu...|
|     MC020|[{true, temperatu...|
+----------+--------------------+
only showing top 20 rows

8. Explode the sensors array.

In [ ]:
exploded_sensors = machine_json.select(
    "machine_id",
    F.explode("sensors").alias("sensor")
)
exploded_sensors.show()

+----------+--------------------+
|machine_id|              sensor|
+----------+--------------------+
|     MC001|{true, temperatur...|
|     MC001|{true, vibration,...|
|     MC001| {true, energy, kWh}|
|     MC002|{true, temperatur...|
|     MC002|{true, vibration,...|
|     MC002| {true, energy, kWh}|
|     MC003|{true, temperatur...|
|     MC003|{true, vibration,...|
|     MC003| {true, energy, kWh}|
|     MC004|{true, temperatur...|
|     MC004|{true, vibration,...|
|     MC004| {true, energy, kWh}|
|     MC005|{true, temperatur...|
|     MC005|{true, vibration,...|
|     MC005| {true, energy, kWh}|
|     MC006|{true, temperatur...|
|     MC006|{true, vibration,...|
|     MC006| {true, energy, kWh}|
|     MC007|{true, temperatur...|
|     MC007|{true, vibration,...|
+----------+--------------------+
only showing top 20 rows

9. Display one row per machine/sensor combination.

In [ ]:
exploded_sensors.select("machine_id", "sensor.*").show()

+----------+------+-----------+----+
|machine_id|active|     sensor|unit|
+----------+------+-----------+----+
|     MC001|  true|temperature|   C|
|     MC001|  true|  vibration|mm/s|
|     MC001|  true|     energy| kWh|
|     MC002|  true|temperature|   C|
|     MC002|  true|  vibration|mm/s|
|     MC002|  true|     energy| kWh|
|     MC003|  true|temperature|   C|
|     MC003|  true|  vibration|mm/s|
|     MC003|  true|     energy| kWh|
|     MC004|  true|temperature|   C|
|     MC004|  true|  vibration|mm/s|
|     MC004|  true|     energy| kWh|
|     MC005|  true|temperature|   C|
|     MC005|  true|  vibration|mm/s|
|     MC005|  true|     energy| kWh|
|     MC006|  true|temperature|   C|
|     MC006|  true|  vibration|mm/s|
|     MC006|  true|     energy| kWh|
|     MC007|  true|temperature|   C|
|     MC007|  true|  vibration|mm/s|
+----------+------+-----------+----+
only showing top 20 rows

10. Find machines having an active temperature sensor.

In [ ]:
exploded_sensors.filter(exploded_sensors["sensor.sensor"] == "temperature").select("machine_id").distinct().show()

+----------+
|machine_id|
+----------+
|     MC003|
|     MC018|
|     MC017|
|     MC009|
|     MC014|
|     MC007|
|     MC002|
|     MC024|
|     MC016|
|     MC026|
|     MC005|
|     MC010|
|     MC012|
|     MC023|
|     MC021|
|     MC020|
|     MC011|
|     MC013|
|     MC025|
|     MC028|
+----------+
only showing top 20 rows

11. Join machine configuration JSON with production data.

In [ ]:
joined_config_df = df.join(machine_json, on="machine_id", how="inner")
joined_config_df.show(5)

+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------+--------------------+--------------+
|machine_id|production_id|production_date|plant_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|capacity_per_hour|installed_year|machine_type|     maintenance|plant_id|             sensors|specifications|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------+--------------------+--------------+
|     MC011|    PR0000001|     2026-08-07|    PL03|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|              100|          2025|         CNC|{30, 2026-04-04}|    PL03|[{true, temperatu...| {90, 30, 6.0}|
|     MC019|    PR0000002|     2026-08-03|    PL04|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|               80|          2021|     Welding|{30, 2026-07-27}|    PL04|[{true, temperatu...| {75, 30, 5.0}|
|     MC002|    PR0000003|     2026-05-20|    PL01|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|               80|          2024|    Assembly|{60, 2026-05-19}|    PL01|[{true, temperatu...| {85, 22, 5.5}|
|     MC013|    PR0000004|     2026-01-15|    PL03|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|              180|          2020|     Casting|{60, 2026-08-03}|    PL03|[{true, temperatu...| {90, 30, 5.0}|
|     MC020|    PR0000005|     2026-09-21|    PL04|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|              120|          2018|     Testing|{45, 2026-09-17}|    PL04|[{true, temperatu...| {80, 15, 5.0}|
+----------+-------------+---------------+--------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------------+------------+----------------+--------+--------------------+--------------+
only showing top 5 rows

**16. Union and Union ALL**

In [ ]:
extra_df = spark.read.csv(
"manufacturing_production_extra_12k.csv",
    header=True,
    inferSchema=True
)

1. Count records in the main DataFrame.

In [ ]:
print(df.count())

120000

2. Count records in the extra DataFrame.

In [ ]:
print(extra_df.count())

12500

3. Combine using union().

In [ ]:
u1 = df.union(extra_df)
u1.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

4. Combine using unionAll().

In [ ]:
u2 = df.unionAll(extra_df)
u2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

5. Compare resulting counts.

In [ ]:
print(u1.count())
print(u2.count())

132500
132500

6. Identify duplicate production_id values.

In [ ]:
u1.groupBy("production_id").count().filter("count > 1").show()

+-------------+-----+
|production_id|count|
+-------------+-----+
|    PR0000413|    2|
|    PR0000135|    2|
|    PR0000236|    2|
|    PR0000339|    2|
|    PR0000059|    2|
|    PR0000463|    2|
|    PR0000136|    2|
|    PR0000263|    2|
|    PR0000393|    2|
|    PR0000445|    2|
|    PR0000124|    2|
|    PR0000299|    2|
|    PR0000341|    2|
|    PR0000008|    2|
|    PR0000172|    2|
|    PR0000359|    2|
|    PR0000389|    2|
|    PR0000026|    2|
|    PR0000274|    2|
|    PR0000161|    2|
+-------------+-----+
only showing top 20 rows

7. Remove duplicates after combining.

In [ ]:
delete_duplicates = u1.dropDuplicates(["production_id"])
delete_duplicates.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000025|     2026-07-28|    PL04|     MC017|     OP0636|Evening|     VLV-220|        Valves|         1139|          1126|             38|              13|    332.97|        58.08|          4.15|          Pass|              No|     Irfan|
|    PR0000026|     2026-04-09|    PL01|     MC001|     OP0604|Evening|     MTR-300|        Motors|          643|           663|             20|              26|    180.36|        63.77|          4.49|          Pass|             Yes|    Charan|
|    PR0000031|     2026-01-04|    PL01|     MC003|     OP0524|Evening|     PMP-210|         Pumps|          762|           776|             49|              28|    238.12|         66.8|          3.09|        Reject|              No|    Bharat|
|    PR0000032|     2026-05-28|    PL06|     MC030|     OP0074|  Night|     CTL-230|   Controllers|          819|           773|             11|              27|     354.3|        63.51|          3.18|          Pass|              No|     Deepa|
|    PR0000036|     2026-07-13|    PL04|     MC020|     OP0559|Evening|     MTR-200|        Motors|          576|           578|              0|              38|    267.36|        70.28|          2.69|          Pass|              No|     Farah|
|    PR0000037|     2026-10-12|    PL06|     MC026|     OP0163|Morning|     MTR-100|        Motors|          633|           626|             15|              56|    173.17|        64.63|           3.7|          Pass|              No|     Irfan|
|    PR0000038|     2026-02-23|    PL02|     MC008|     OP0114|  Night|     MTR-300|        Motors|          864|           867|              6|              38|    335.24|         53.7|           3.0|          Pass|              No|     Anita|
|    PR0000039|     2026-07-17|    PL01|     MC002|     OP0220|  Night|     VLV-120|        Valves|          260|           265|              0|               2|    127.18|        51.87|          3.41|          Pass|              No|     Irfan|
|    PR0000041|     2026-05-14|    PL02|     MC009|     OP0192|Morning|     PMP-310|         Pumps|          711|           664|             32|              60|    335.84|        57.87|           3.2|          Pass|             Yes|     Irfan|
|    PR0000046|     2026-04-02|    PL06|     MC027|     OP0484|Morning|     VLV-120|        Valves|          847|           778|             19|             145|    381.88|        63.42|          2.94|        Reject|              No|     Anita|
|    PR0000047|     2026-01-22|    PL06|     MC028|     OP0512|Evening|     PMP-110|         Pumps|          956|           882|              4|             118|     247.4|         NULL|          2.52|          Pass|              No|    Charan|
|    PR0000048|     2026-03-08|    PL03|     MC015|     OP0110|Morning|     CTL-230|   Controllers|          858|           810|              0|               0|    250.54|        58.93|          4.04|          Pass|              No|    Bharat|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

8. Compare unioned count before and after dropDuplicates().

In [ ]:
print("Before:", u1.count())
print("After:", delete_duplicates.count())

Before: 132500
After: 132000

9. Try unionByName().

In [ ]:
u3 = df.unionByName(extra_df)
u3.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

10. Rearrange columns in one DataFrame and use unionByName() appropriately.

In [ ]:
reordered = extra_df.select(*reversed(extra_df.columns))
u4 = df.unionByName(reordered)
print(u4.count())

132500

**17. Window Functions**

In [ ]:
from pyspark.sql.window import Window

In [ ]:
w_plant_units = Window.partitionBy("plant_id").orderBy("units_produced")

1. Rank production records within each plant by units produced.

In [ ]:
df2 = df.withColumn("rank", F.rank().over(w_plant_units))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|rank|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|   1|
|    PR0032002|     2026-07-05|    PL02|     MC007|     OP0649|Morning|     PMP-110|         Pumps|          256|           210|              6|              10|     95.79|        63.07|          4.08|          Pass|              No|    Harini|   2|
|    PR0047306|     2026-09-01|    PL02|     MC006|     OP0266|Evening|     CTL-330|   Controllers|          256|           210|              3|              79|     80.45|        60.97|          4.09|        Reject|              No|    Bharat|   2|
|    PR0113308|     2026-02-13|    PL02|     MC010|     OP0289|  Night|     CTL-230|   Controllers|          253|           210|              5|              31|      50.0|        64.88|          2.84|          Pass|              No|     Deepa|   2|
|    PR0108483|     2026-01-06|    PL02|     MC006|     OP0087|Evening|     VLV-120|        Valves|          253|           212|              7|              17|    105.25|        77.01|          1.14|          Pass|              No|     Anita|   5|
|    PR0018956|     2026-09-20|    PL02|     MC006|     OP0503|Morning|     PMP-110|         Pumps|          255|           213|              2|              36|     94.97|        74.51|          3.61|        Reject|              No|     Anita|   6|
|    PR0059984|     2026-04-28|    PL02|     MC006|     OP0358|  Night|     MTR-200|        Motors|          259|           213|              5|              45|    102.15|        63.33|           2.4|        Reject|              No|     Gopal|   6|
|    PR0090786|     2026-10-22|    PL02|     MC009|     OP0624|Evening|     MTR-100|        Motors|          252|           213|              8|              36|     68.49|        68.46|          5.15|          Pass|              No|     Deepa|   6|
|    PR0093689|     2026-04-15|    PL02|     MC010|     OP0533|Evening|     VLV-320|        Valves|          254|           213|              6|              10|     54.44|        60.41|          1.11|          Pass|             Yes|     Gopal|   6|
|    PR0113820|     2026-01-28|    PL02|     MC008|     OP0051|  Night|     CTL-230|   Controllers|          257|           213|              0|              28|    107.37|        53.84|          2.07|          Pass|              No|    Bharat|   6|
|    PR0002484|     2026-02-27|    PL02|     MC006|     OP0627|Evening|     VLV-220|        Valves|          261|           214|              7|              16|    106.11|        62.95|          1.85|        Reject|              No|     Farah|  11|
|    PR0006619|     2026-07-29|    PL02|     MC008|     OP0013|  Night|     VLV-320|        Valves|          257|           214|              3|              45|     62.86|        66.79|          2.92|          Pass|             Yes|     Irfan|  11|
|    PR0055751|     2026-04-25|    PL02|     MC007|     OP0042|Morning|     MTR-100|        Motors|          252|           214|              4|             204|     75.36|        70.12|          3.13|          Pass|              No|     Irfan|  11|
|    PR0095543|     2026-02-28|    PL02|     MC007|     OP0243|Morning|     VLV-120|        Valves|          259|           214|              3|              77|      50.0|        53.28|           5.9|          Pass|             Yes|    Harini|  11|
|    PR0112329|     2026-04-20|    PL02|     MC006|     OP0020|Evening|     CTL-230|   Controllers|          258|           214|             11|               3|     56.35|        71.63|           2.3|          Pass|              No|    Bharat|  11|
|    PR0013018|     2026-05-25|    PL02|     MC009|     OP0426|Morning|     VLV-320|        Valves|          254|           215|              1|               7|      50.0|        54.93|          3.41|          Pass|              No|     Irfan|  16|
|    PR0035301|     2026-08-26|    PL02|     MC009|     OP0340|Evening|     CTL-230|   Controllers|          255|           215|              3|              25|      83.3|        71.01|          1.89|        Reject|              No|    Charan|  16|
|    PR0118353|     2026-03-24|    PL02|     MC008|     OP0072|  Night|     CTL-130|   Controllers|          255|           215|              3|              10|     55.48|        66.66|          4.12|          Pass|              No|     Farah|  16|
|    PR0014352|     2026-10-20|    PL02|     MC010|     OP0648|Morning|     MTR-100|        Motors|          252|           216|              5|              26|      50.0|        55.94|          3.05|          Pass|              No|    Bharat|  19|
|    PR0026782|     2026-10-16|    PL02|     MC009|     OP0573|  Night|     MTR-200|        Motors|          255|           216|              2|              11|      50.0|        58.13|          3.98|        Reject|              No|     Deepa|  19|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
only showing top 20 rows

2. Use row_number().

In [ ]:
df2 = df.withColumn("row_number", F.row_number().over(w_plant_units))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|row_number|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|         1|
|    PR0032002|     2026-07-05|    PL02|     MC007|     OP0649|Morning|     PMP-110|         Pumps|          256|           210|              6|              10|     95.79|        63.07|          4.08|          Pass|              No|    Harini|         2|
|    PR0047306|     2026-09-01|    PL02|     MC006|     OP0266|Evening|     CTL-330|   Controllers|          256|           210|              3|              79|     80.45|        60.97|          4.09|        Reject|              No|    Bharat|         3|
|    PR0113308|     2026-02-13|    PL02|     MC010|     OP0289|  Night|     CTL-230|   Controllers|          253|           210|              5|              31|      50.0|        64.88|          2.84|          Pass|              No|     Deepa|         4|
|    PR0108483|     2026-01-06|    PL02|     MC006|     OP0087|Evening|     VLV-120|        Valves|          253|           212|              7|              17|    105.25|        77.01|          1.14|          Pass|              No|     Anita|         5|
|    PR0018956|     2026-09-20|    PL02|     MC006|     OP0503|Morning|     PMP-110|         Pumps|          255|           213|              2|              36|     94.97|        74.51|          3.61|        Reject|              No|     Anita|         6|
|    PR0059984|     2026-04-28|    PL02|     MC006|     OP0358|  Night|     MTR-200|        Motors|          259|           213|              5|              45|    102.15|        63.33|           2.4|        Reject|              No|     Gopal|         7|
|    PR0090786|     2026-10-22|    PL02|     MC009|     OP0624|Evening|     MTR-100|        Motors|          252|           213|              8|              36|     68.49|        68.46|          5.15|          Pass|              No|     Deepa|         8|
|    PR0093689|     2026-04-15|    PL02|     MC010|     OP0533|Evening|     VLV-320|        Valves|          254|           213|              6|              10|     54.44|        60.41|          1.11|          Pass|             Yes|     Gopal|         9|
|    PR0113820|     2026-01-28|    PL02|     MC008|     OP0051|  Night|     CTL-230|   Controllers|          257|           213|              0|              28|    107.37|        53.84|          2.07|          Pass|              No|    Bharat|        10|
|    PR0002484|     2026-02-27|    PL02|     MC006|     OP0627|Evening|     VLV-220|        Valves|          261|           214|              7|              16|    106.11|        62.95|          1.85|        Reject|              No|     Farah|        11|
|    PR0006619|     2026-07-29|    PL02|     MC008|     OP0013|  Night|     VLV-320|        Valves|          257|           214|              3|              45|     62.86|        66.79|          2.92|          Pass|             Yes|     Irfan|        12|
|    PR0055751|     2026-04-25|    PL02|     MC007|     OP0042|Morning|     MTR-100|        Motors|          252|           214|              4|             204|     75.36|        70.12|          3.13|          Pass|              No|     Irfan|        13|
|    PR0095543|     2026-02-28|    PL02|     MC007|     OP0243|Morning|     VLV-120|        Valves|          259|           214|              3|              77|      50.0|        53.28|           5.9|          Pass|             Yes|    Harini|        14|
|    PR0112329|     2026-04-20|    PL02|     MC006|     OP0020|Evening|     CTL-230|   Controllers|          258|           214|             11|               3|     56.35|        71.63|           2.3|          Pass|              No|    Bharat|        15|
|    PR0013018|     2026-05-25|    PL02|     MC009|     OP0426|Morning|     VLV-320|        Valves|          254|           215|              1|               7|      50.0|        54.93|          3.41|          Pass|              No|     Irfan|        16|
|    PR0035301|     2026-08-26|    PL02|     MC009|     OP0340|Evening|     CTL-230|   Controllers|          255|           215|              3|              25|      83.3|        71.01|          1.89|        Reject|              No|    Charan|        17|
|    PR0118353|     2026-03-24|    PL02|     MC008|     OP0072|  Night|     CTL-130|   Controllers|          255|           215|              3|              10|     55.48|        66.66|          4.12|          Pass|              No|     Farah|        18|
|    PR0014352|     2026-10-20|    PL02|     MC010|     OP0648|Morning|     MTR-100|        Motors|          252|           216|              5|              26|      50.0|        55.94|          3.05|          Pass|              No|    Bharat|        19|
|    PR0026782|     2026-10-16|    PL02|     MC009|     OP0573|  Night|     MTR-200|        Motors|          255|           216|              2|              11|      50.0|        58.13|          3.98|        Reject|              No|     Deepa|        20|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
only showing top 20 rows

3. Use rank().

In [ ]:
df2 = df.withColumn("rank", F.rank().over(w_plant_units))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|rank|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|   1|
|    PR0032002|     2026-07-05|    PL02|     MC007|     OP0649|Morning|     PMP-110|         Pumps|          256|           210|              6|              10|     95.79|        63.07|          4.08|          Pass|              No|    Harini|   2|
|    PR0047306|     2026-09-01|    PL02|     MC006|     OP0266|Evening|     CTL-330|   Controllers|          256|           210|              3|              79|     80.45|        60.97|          4.09|        Reject|              No|    Bharat|   2|
|    PR0113308|     2026-02-13|    PL02|     MC010|     OP0289|  Night|     CTL-230|   Controllers|          253|           210|              5|              31|      50.0|        64.88|          2.84|          Pass|              No|     Deepa|   2|
|    PR0108483|     2026-01-06|    PL02|     MC006|     OP0087|Evening|     VLV-120|        Valves|          253|           212|              7|              17|    105.25|        77.01|          1.14|          Pass|              No|     Anita|   5|
|    PR0018956|     2026-09-20|    PL02|     MC006|     OP0503|Morning|     PMP-110|         Pumps|          255|           213|              2|              36|     94.97|        74.51|          3.61|        Reject|              No|     Anita|   6|
|    PR0059984|     2026-04-28|    PL02|     MC006|     OP0358|  Night|     MTR-200|        Motors|          259|           213|              5|              45|    102.15|        63.33|           2.4|        Reject|              No|     Gopal|   6|
|    PR0090786|     2026-10-22|    PL02|     MC009|     OP0624|Evening|     MTR-100|        Motors|          252|           213|              8|              36|     68.49|        68.46|          5.15|          Pass|              No|     Deepa|   6|
|    PR0093689|     2026-04-15|    PL02|     MC010|     OP0533|Evening|     VLV-320|        Valves|          254|           213|              6|              10|     54.44|        60.41|          1.11|          Pass|             Yes|     Gopal|   6|
|    PR0113820|     2026-01-28|    PL02|     MC008|     OP0051|  Night|     CTL-230|   Controllers|          257|           213|              0|              28|    107.37|        53.84|          2.07|          Pass|              No|    Bharat|   6|
|    PR0002484|     2026-02-27|    PL02|     MC006|     OP0627|Evening|     VLV-220|        Valves|          261|           214|              7|              16|    106.11|        62.95|          1.85|        Reject|              No|     Farah|  11|
|    PR0006619|     2026-07-29|    PL02|     MC008|     OP0013|  Night|     VLV-320|        Valves|          257|           214|              3|              45|     62.86|        66.79|          2.92|          Pass|             Yes|     Irfan|  11|
|    PR0055751|     2026-04-25|    PL02|     MC007|     OP0042|Morning|     MTR-100|        Motors|          252|           214|              4|             204|     75.36|        70.12|          3.13|          Pass|              No|     Irfan|  11|
|    PR0095543|     2026-02-28|    PL02|     MC007|     OP0243|Morning|     VLV-120|        Valves|          259|           214|              3|              77|      50.0|        53.28|           5.9|          Pass|             Yes|    Harini|  11|
|    PR0112329|     2026-04-20|    PL02|     MC006|     OP0020|Evening|     CTL-230|   Controllers|          258|           214|             11|               3|     56.35|        71.63|           2.3|          Pass|              No|    Bharat|  11|
|    PR0013018|     2026-05-25|    PL02|     MC009|     OP0426|Morning|     VLV-320|        Valves|          254|           215|              1|               7|      50.0|        54.93|          3.41|          Pass|              No|     Irfan|  16|
|    PR0035301|     2026-08-26|    PL02|     MC009|     OP0340|Evening|     CTL-230|   Controllers|          255|           215|              3|              25|      83.3|        71.01|          1.89|        Reject|              No|    Charan|  16|
|    PR0118353|     2026-03-24|    PL02|     MC008|     OP0072|  Night|     CTL-130|   Controllers|          255|           215|              3|              10|     55.48|        66.66|          4.12|          Pass|              No|     Farah|  16|
|    PR0014352|     2026-10-20|    PL02|     MC010|     OP0648|Morning|     MTR-100|        Motors|          252|           216|              5|              26|      50.0|        55.94|          3.05|          Pass|              No|    Bharat|  19|
|    PR0026782|     2026-10-16|    PL02|     MC009|     OP0573|  Night|     MTR-200|        Motors|          255|           216|              2|              11|      50.0|        58.13|          3.98|        Reject|              No|     Deepa|  19|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
only showing top 20 rows

4. Use dense_rank().

In [ ]:
df2 = df.withColumn("dense_rank", F.dense_rank().over(w_plant_units))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|dense_rank|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|         1|
|    PR0032002|     2026-07-05|    PL02|     MC007|     OP0649|Morning|     PMP-110|         Pumps|          256|           210|              6|              10|     95.79|        63.07|          4.08|          Pass|              No|    Harini|         2|
|    PR0047306|     2026-09-01|    PL02|     MC006|     OP0266|Evening|     CTL-330|   Controllers|          256|           210|              3|              79|     80.45|        60.97|          4.09|        Reject|              No|    Bharat|         2|
|    PR0113308|     2026-02-13|    PL02|     MC010|     OP0289|  Night|     CTL-230|   Controllers|          253|           210|              5|              31|      50.0|        64.88|          2.84|          Pass|              No|     Deepa|         2|
|    PR0108483|     2026-01-06|    PL02|     MC006|     OP0087|Evening|     VLV-120|        Valves|          253|           212|              7|              17|    105.25|        77.01|          1.14|          Pass|              No|     Anita|         3|
|    PR0018956|     2026-09-20|    PL02|     MC006|     OP0503|Morning|     PMP-110|         Pumps|          255|           213|              2|              36|     94.97|        74.51|          3.61|        Reject|              No|     Anita|         4|
|    PR0059984|     2026-04-28|    PL02|     MC006|     OP0358|  Night|     MTR-200|        Motors|          259|           213|              5|              45|    102.15|        63.33|           2.4|        Reject|              No|     Gopal|         4|
|    PR0090786|     2026-10-22|    PL02|     MC009|     OP0624|Evening|     MTR-100|        Motors|          252|           213|              8|              36|     68.49|        68.46|          5.15|          Pass|              No|     Deepa|         4|
|    PR0093689|     2026-04-15|    PL02|     MC010|     OP0533|Evening|     VLV-320|        Valves|          254|           213|              6|              10|     54.44|        60.41|          1.11|          Pass|             Yes|     Gopal|         4|
|    PR0113820|     2026-01-28|    PL02|     MC008|     OP0051|  Night|     CTL-230|   Controllers|          257|           213|              0|              28|    107.37|        53.84|          2.07|          Pass|              No|    Bharat|         4|
|    PR0002484|     2026-02-27|    PL02|     MC006|     OP0627|Evening|     VLV-220|        Valves|          261|           214|              7|              16|    106.11|        62.95|          1.85|        Reject|              No|     Farah|         5|
|    PR0006619|     2026-07-29|    PL02|     MC008|     OP0013|  Night|     VLV-320|        Valves|          257|           214|              3|              45|     62.86|        66.79|          2.92|          Pass|             Yes|     Irfan|         5|
|    PR0055751|     2026-04-25|    PL02|     MC007|     OP0042|Morning|     MTR-100|        Motors|          252|           214|              4|             204|     75.36|        70.12|          3.13|          Pass|              No|     Irfan|         5|
|    PR0095543|     2026-02-28|    PL02|     MC007|     OP0243|Morning|     VLV-120|        Valves|          259|           214|              3|              77|      50.0|        53.28|           5.9|          Pass|             Yes|    Harini|         5|
|    PR0112329|     2026-04-20|    PL02|     MC006|     OP0020|Evening|     CTL-230|   Controllers|          258|           214|             11|               3|     56.35|        71.63|           2.3|          Pass|              No|    Bharat|         5|
|    PR0013018|     2026-05-25|    PL02|     MC009|     OP0426|Morning|     VLV-320|        Valves|          254|           215|              1|               7|      50.0|        54.93|          3.41|          Pass|              No|     Irfan|         6|
|    PR0035301|     2026-08-26|    PL02|     MC009|     OP0340|Evening|     CTL-230|   Controllers|          255|           215|              3|              25|      83.3|        71.01|          1.89|        Reject|              No|    Charan|         6|
|    PR0118353|     2026-03-24|    PL02|     MC008|     OP0072|  Night|     CTL-130|   Controllers|          255|           215|              3|              10|     55.48|        66.66|          4.12|          Pass|              No|     Farah|         6|
|    PR0014352|     2026-10-20|    PL02|     MC010|     OP0648|Morning|     MTR-100|        Motors|          252|           216|              5|              26|      50.0|        55.94|          3.05|          Pass|              No|    Bharat|         7|
|    PR0026782|     2026-10-16|    PL02|     MC009|     OP0573|  Night|     MTR-200|        Motors|          255|           216|              2|              11|      50.0|        58.13|          3.98|        Reject|              No|     Deepa|         7|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+
only showing top 20 rows

5. Find top 5 production runs per plant.

In [ ]:
df2 = df.withColumn("rank", F.rank().over(w_plant_units))
df2.filter(df2["rank"] <= 5).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|rank|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
|    PR0030899|     2026-05-24|    PL01|     MC004|     OP0380|Evening|     VLV-120|        Valves|          252|           206|             12|              12|     75.94|        50.77|          3.34|        Rework|              No|     Farah|   1|
|    PR0039880|     2026-01-04|    PL01|     MC005|     OP0034|Evening|     PMP-210|         Pumps|          250|           206|              0|              38|      50.0|        64.38|          2.33|        Rework|              No|     Deepa|   1|
|    PR0071924|     2026-05-26|    PL01|     MC003|     OP0120|  Night|     PMP-210|         Pumps|          251|           206|              9|              40|      50.0|        52.13|          2.54|          Pass|              No|     Irfan|   1|
|    PR0065998|     2026-05-08|    PL01|     MC004|     OP0090|Morning|     PMP-310|         Pumps|          250|           208|              3|              29|    102.63|         48.1|          4.19|          Pass|              No|    Bharat|   4|
|    PR0113148|     2026-01-31|    PL01|     MC004|     OP0219|Morning|     CTL-230|   Controllers|          252|           208|              2|              27|      50.0|        63.72|          4.23|          Pass|              No|     Gopal|   4|
|    PR0114652|     2026-08-23|    PL01|     MC001|     OP0529|Evening|     VLV-220|        Valves|          250|           208|              0|              17|     90.71|        50.34|          3.76|          Pass|              No|    Charan|   4|
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|   1|
|    PR0032002|     2026-07-05|    PL02|     MC007|     OP0649|Morning|     PMP-110|         Pumps|          256|           210|              6|              10|     95.79|        63.07|          4.08|          Pass|              No|    Harini|   2|
|    PR0047306|     2026-09-01|    PL02|     MC006|     OP0266|Evening|     CTL-330|   Controllers|          256|           210|              3|              79|     80.45|        60.97|          4.09|        Reject|              No|    Bharat|   2|
|    PR0113308|     2026-02-13|    PL02|     MC010|     OP0289|  Night|     CTL-230|   Controllers|          253|           210|              5|              31|      50.0|        64.88|          2.84|          Pass|              No|     Deepa|   2|
|    PR0108483|     2026-01-06|    PL02|     MC006|     OP0087|Evening|     VLV-120|        Valves|          253|           212|              7|              17|    105.25|        77.01|          1.14|          Pass|              No|     Anita|   5|
|    PR0013719|     2026-04-30|    PL03|     MC014|     OP0340|Morning|     MTR-200|        Motors|          250|           206|              5|              82|     62.29|        55.57|           2.4|          Pass|              No|    Harini|   1|
|    PR0020293|     2026-08-08|    PL03|     MC014|     OP0567|Evening|     CTL-130|   Controllers|          253|           207|              5|              37|      50.0|        64.89|          1.81|          Pass|              No|     Deepa|   2|
|    PR0107410|     2026-09-29|    PL03|     MC012|     OP0237|Evening|     VLV-120|        Valves|          252|           207|              8|              36|     99.97|        61.39|          3.94|          Pass|              No|     Deepa|   2|
|    PR0062368|     2026-02-08|    PL03|     MC015|     OP0376|Morning|     VLV-220|        Valves|          255|           209|             12|              37|      50.0|        49.94|          0.63|        Rework|              No|    Bharat|   4|
|    PR0107334|     2026-07-21|    PL03|     MC011|     OP0648|Morning|     MTR-300|        Motors|          254|           209|              9|              19|     79.84|        39.55|          3.45|        Rework|              No|     Farah|   4|
|    PR0079337|     2026-05-05|    PL04|     MC018|     OP0623|Evening|     PMP-210|         Pumps|          251|           206|              0|               0|     77.66|        67.78|          2.36|        Rework|              No|     Irfan|   1|
|    PR0087182|     2026-09-03|    PL04|     MC019|     OP0196|Evening|     CTL-330|   Controllers|          250|           206|              4|              13|     98.25|        59.27|          6.99|        Reject|             Yes|     Irfan|   1|
|    PR0115075|     2026-10-03|    PL04|     MC019|     OP0014|  Night|     CTL-130|   Controllers|          251|           206|              1|              66|     79.31|         78.2|          4.21|        Rework|              No|    Bharat|   1|
|    PR0028542|     2026-04-10|    PL04|     MC020|     OP0325|Evening|     CTL-230|   Controllers|          251|           207|              8|              18|     93.84|         64.9|          1.55|          Pass|              No|     Anita|   4|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
only showing top 20 rows

6. Find top 3 machines by output within each plant.

In [ ]:
machine_totals = Window.partitionBy("plant_id").orderBy(F.desc("units_produced"))
df2 = df.withColumn("rank", F.rank().over(machine_totals))
df2.filter(df2["rank"] <= 3).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|rank|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|   1|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|   2|
|    PR0005192|     2026-09-08|    PL01|     MC002|     OP0075|Morning|     MTR-300|        Motors|         1195|          1236|             12|              49|    349.97|         81.8|          2.95|          Pass|              No|     Gopal|   3|
|    PR0044516|     2026-10-10|    PL01|     MC002|     OP0513|Morning|     MTR-200|        Motors|         1200|          1236|             25|              37|    233.63|        75.95|          1.82|          Pass|              No|     Gopal|   3|
|    PR0056319|     2026-06-07|    PL01|     MC002|     OP0453|Evening|     CTL-130|   Controllers|         1193|          1236|              4|              24|    617.25|        46.98|          4.71|          Pass|             Yes|     Farah|   3|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|   1|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|   2|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|   3|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|   1|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|   2|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|   2|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|   1|
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|   1|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|   3|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|   1|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|   2|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|   3|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|   1|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|   2|
|    PR0070732|     2026-07-24|    PL06|     MC027|     OP0336|Morning|     VLV-120|        Valves|         1196|          1237|             62|              52|    496.14|        61.64|          3.67|        Rework|              No|    Charan|   3|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+

7. Calculate total plant production without collapsing rows.

In [ ]:
df2 = df.withColumn("total_production", F.sum("units_produced").over(w_plant_units))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|total_production|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------------+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|             205|
|    PR0032002|     2026-07-05|    PL02|     MC007|     OP0649|Morning|     PMP-110|         Pumps|          256|           210|              6|              10|     95.79|        63.07|          4.08|          Pass|              No|    Harini|             835|
|    PR0047306|     2026-09-01|    PL02|     MC006|     OP0266|Evening|     CTL-330|   Controllers|          256|           210|              3|              79|     80.45|        60.97|          4.09|        Reject|              No|    Bharat|             835|
|    PR0113308|     2026-02-13|    PL02|     MC010|     OP0289|  Night|     CTL-230|   Controllers|          253|           210|              5|              31|      50.0|        64.88|          2.84|          Pass|              No|     Deepa|             835|
|    PR0108483|     2026-01-06|    PL02|     MC006|     OP0087|Evening|     VLV-120|        Valves|          253|           212|              7|              17|    105.25|        77.01|          1.14|          Pass|              No|     Anita|            1047|
|    PR0018956|     2026-09-20|    PL02|     MC006|     OP0503|Morning|     PMP-110|         Pumps|          255|           213|              2|              36|     94.97|        74.51|          3.61|        Reject|              No|     Anita|            2112|
|    PR0059984|     2026-04-28|    PL02|     MC006|     OP0358|  Night|     MTR-200|        Motors|          259|           213|              5|              45|    102.15|        63.33|           2.4|        Reject|              No|     Gopal|            2112|
|    PR0090786|     2026-10-22|    PL02|     MC009|     OP0624|Evening|     MTR-100|        Motors|          252|           213|              8|              36|     68.49|        68.46|          5.15|          Pass|              No|     Deepa|            2112|
|    PR0093689|     2026-04-15|    PL02|     MC010|     OP0533|Evening|     VLV-320|        Valves|          254|           213|              6|              10|     54.44|        60.41|          1.11|          Pass|             Yes|     Gopal|            2112|
|    PR0113820|     2026-01-28|    PL02|     MC008|     OP0051|  Night|     CTL-230|   Controllers|          257|           213|              0|              28|    107.37|        53.84|          2.07|          Pass|              No|    Bharat|            2112|
|    PR0002484|     2026-02-27|    PL02|     MC006|     OP0627|Evening|     VLV-220|        Valves|          261|           214|              7|              16|    106.11|        62.95|          1.85|        Reject|              No|     Farah|            3182|
|    PR0006619|     2026-07-29|    PL02|     MC008|     OP0013|  Night|     VLV-320|        Valves|          257|           214|              3|              45|     62.86|        66.79|          2.92|          Pass|             Yes|     Irfan|            3182|
|    PR0055751|     2026-04-25|    PL02|     MC007|     OP0042|Morning|     MTR-100|        Motors|          252|           214|              4|             204|     75.36|        70.12|          3.13|          Pass|              No|     Irfan|            3182|
|    PR0095543|     2026-02-28|    PL02|     MC007|     OP0243|Morning|     VLV-120|        Valves|          259|           214|              3|              77|      50.0|        53.28|           5.9|          Pass|             Yes|    Harini|            3182|
|    PR0112329|     2026-04-20|    PL02|     MC006|     OP0020|Evening|     CTL-230|   Controllers|          258|           214|             11|               3|     56.35|        71.63|           2.3|          Pass|              No|    Bharat|            3182|
|    PR0013018|     2026-05-25|    PL02|     MC009|     OP0426|Morning|     VLV-320|        Valves|          254|           215|              1|               7|      50.0|        54.93|          3.41|          Pass|              No|     Irfan|            3827|
|    PR0035301|     2026-08-26|    PL02|     MC009|     OP0340|Evening|     CTL-230|   Controllers|          255|           215|              3|              25|      83.3|        71.01|          1.89|        Reject|              No|    Charan|            3827|
|    PR0118353|     2026-03-24|    PL02|     MC008|     OP0072|  Night|     CTL-130|   Controllers|          255|           215|              3|              10|     55.48|        66.66|          4.12|          Pass|              No|     Farah|            3827|
|    PR0014352|     2026-10-20|    PL02|     MC010|     OP0648|Morning|     MTR-100|        Motors|          252|           216|              5|              26|      50.0|        55.94|          3.05|          Pass|              No|    Bharat|            5123|
|    PR0026782|     2026-10-16|    PL02|     MC009|     OP0573|  Night|     MTR-200|        Motors|          255|           216|              2|              11|      50.0|        58.13|          3.98|        Reject|              No|     Deepa|            5123|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------------+
only showing top 20 rows

8. Calculate average machine output using a window.

In [ ]:
w_machine = Window.partitionBy("machine_id")
df2 = df.withColumn("avg_output", F.avg("units_produced").over(w_machine))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|       avg_output|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|672.7265741199801|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|672.7265741199801|
|    PR0000039|     2026-07-17|    PL01|     MC002|     OP0220|  Night|     VLV-120|        Valves|          260|           265|              0|               2|    127.18|        51.87|          3.41|          Pass|              No|     Irfan|672.7265741199801|
|    PR0000063|     2026-02-18|    PL01|     MC002|     OP0390|  Night|     VLV-120|        Valves|          656|           665|              0|              44|     311.8|        58.34|           2.0|          Pass|              No|     Deepa|672.7265741199801|
|    PR0000132|     2026-03-27|    PL01|     MC002|     OP0123|Evening|     CTL-330|   Controllers|         1069|           928|             11|              11|    198.07|        64.63|          3.73|        Reject|              No|    Harini|672.7265741199801|
|    PR0000154|     2026-08-19|    PL01|     MC002|     OP0624|Morning|     PMP-310|         Pumps|          508|           450|              8|              43|    231.23|        53.02|           3.1|        Rework|              No|    Charan|672.7265741199801|
|    PR0000200|     2026-01-11|    PL01|     MC002|     OP0338|Evening|     PMP-110|         Pumps|         1146|          1051|             33|              70|    460.46|        47.92|          NULL|        Reject|              No|     Irfan|672.7265741199801|
|    PR0000233|     2026-04-20|    PL01|     MC002|     OP0437|  Night|     MTR-300|        Motors|         1084|           947|             53|              59|    404.27|        69.34|          2.31|        Reject|              No|    Charan|672.7265741199801|
|    PR0000264|     2026-07-11|    PL01|     MC002|     OP0607|Evening|     CTL-330|   Controllers|          904|           866|             12|              36|    254.73|        75.26|          4.05|          Pass|              No|    Harini|672.7265741199801|
|    PR0000268|     2026-07-24|    PL01|     MC002|     OP0537|  Night|     CTL-330|   Controllers|          668|           584|              4|               0|    217.65|        73.71|          5.29|          Pass|              No|    Harini|672.7265741199801|
|    PR0000284|     2026-01-17|    PL01|     MC002|     OP0071|Evening|     CTL-130|   Controllers|         1118|          1053|              0|              33|    485.67|        62.18|          3.95|        Reject|              No|     Irfan|672.7265741199801|
|    PR0000335|     2026-09-29|    PL01|     MC002|     OP0503|Evening|     CTL-230|   Controllers|          334|           274|              3|              22|    118.09|        67.57|          4.64|          Pass|              No|     Deepa|672.7265741199801|
|    PR0000383|     2026-10-08|    PL01|     MC002|     OP0482|Morning|     MTR-200|        Motors|          290|           244|             13|             171|     57.48|         78.1|          1.37|          Pass|              No|    Bharat|672.7265741199801|
|    PR0000402|     2026-10-22|    PL01|     MC002|     OP0516|Evening|     VLV-120|        Valves|         1150|           983|             30|              57|    264.33|        57.85|          2.94|          Pass|             Yes|    Harini|672.7265741199801|
|    PR0000405|     2026-05-14|    PL01|     MC002|     OP0308|Evening|     MTR-100|        Motors|         1170|          1127|             30|              30|    350.16|        61.28|          3.89|          Pass|             Yes|     Anita|672.7265741199801|
|    PR0000482|     2026-08-05|    PL01|     MC002|     OP0579|Evening|     MTR-200|        Motors|         1085|           925|             20|              14|    298.76|        59.72|          2.39|        Rework|              No|     Farah|672.7265741199801|
|    PR0000576|     2026-04-25|    PL01|     MC002|     OP0192|Evening|     MTR-200|        Motors|          940|           806|              0|              57|    380.36|        53.91|          2.99|          Pass|              No|     Irfan|672.7265741199801|
|    PR0000594|     2026-06-24|    PL01|     MC002|     OP0134|  Night|     PMP-110|         Pumps|          809|           815|              0|              74|    422.07|        60.19|          3.62|        Rework|             Yes|     Anita|672.7265741199801|
|    PR0000637|     2026-02-21|    PL01|     MC002|     OP0017|Evening|     PMP-310|         Pumps|          492|           448|             15|               6|    184.84|         59.1|          2.88|        Reject|              No|     Anita|672.7265741199801|
|    PR0000699|     2026-06-06|    PL01|     MC002|     OP0555|  Night|     CTL-230|   Controllers|         1014|           875|             31|              30|    251.46|         70.3|           0.4|          Pass|              No|     Deepa|672.7265741199801|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+
only showing top 20 rows

9. Calculate cumulative production by machine ordered by date.

In [ ]:
df2 = df.withColumn("cumulative_production", F.sum("units_produced").over(Window.partitionBy("machine_id").orderBy("production_date")))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|cumulative_production|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
|    PR0001004|     2026-01-01|    PL01|     MC002|     OP0424|  Night|     VLV-120|        Valves|          517|           520|             14|               0|    133.77|        52.65|          4.53|          Pass|              No|    Harini|                12680|
|    PR0003457|     2026-01-01|    PL01|     MC002|     OP0300|  Night|     CTL-330|   Controllers|          757|           660|             34|              38|    160.47|        58.86|          2.55|        Rework|              No|    Harini|                12680|
|    PR0004579|     2026-01-01|    PL01|     MC002|     OP0648|Morning|     PMP-110|         Pumps|          382|           362|             13|               4|     67.29|         70.7|          4.44|          Pass|              No|     Gopal|                12680|
|    PR0007449|     2026-01-01|    PL01|     MC002|     OP0435|Evening|     CTL-130|   Controllers|          433|           420|              6|              11|    161.43|        59.12|          3.14|          Pass|              No|    Harini|                12680|
|    PR0014425|     2026-01-01|    PL01|     MC002|     OP0041|Morning|     MTR-200|        Motors|          737|           710|              4|              12|    338.49|        71.22|          2.29|          Pass|              No|    Harini|                12680|
|    PR0017340|     2026-01-01|    PL01|     MC002|     OP0556|Evening|     VLV-320|        Valves|          988|           829|             22|              55|    309.43|        67.98|          4.63|          Pass|              No|     Farah|                12680|
|    PR0021804|     2026-01-01|    PL01|     MC002|     OP0220|Morning|     CTL-130|   Controllers|         1099|          1064|             31|              41|    441.84|        70.18|          3.49|          Pass|              No|     Anita|                12680|
|    PR0039968|     2026-01-01|    PL01|     MC002|     OP0309|  Night|     VLV-120|        Valves|         1127|          1159|             41|              45|    320.98|        72.94|           4.3|          Pass|              No|     Irfan|                12680|
|    PR0051741|     2026-01-01|    PL01|     MC002|     OP0549|Morning|     CTL-330|   Controllers|          311|           261|              6|              22|     61.65|        53.85|          3.03|        Reject|              No|    Charan|                12680|
|    PR0062464|     2026-01-01|    PL01|     MC002|     OP0199|  Night|     PMP-110|         Pumps|          920|           853|             14|              46|    367.01|         NULL|          3.89|        Reject|              No|    Harini|                12680|
|    PR0063055|     2026-01-01|    PL01|     MC002|     OP0218|Evening|     PMP-310|         Pumps|         1124|          1022|              2|               0|    377.08|        68.29|          4.82|          Pass|              No|     Gopal|                12680|
|    PR0064058|     2026-01-01|    PL01|     MC002|     OP0166|Morning|     VLV-320|        Valves|          602|           606|              0|              49|     310.0|        59.54|           0.8|          Pass|              No|     Farah|                12680|
|    PR0074326|     2026-01-01|    PL01|     MC002|     OP0271|  Night|     VLV-220|        Valves|         1141|          1106|             35|             121|     440.6|        63.09|          0.91|          Pass|             Yes|    Bharat|                12680|
|    PR0081104|     2026-01-01|    PL01|     MC002|     OP0490|Evening|     MTR-200|        Motors|          877|           769|             30|              72|    267.64|        66.52|          3.07|          Pass|              No|     Gopal|                12680|
|    PR0084720|     2026-01-01|    PL01|     MC002|     OP0132|  Night|     PMP-110|         Pumps|         1102|           929|             34|               0|    367.07|        57.04|          1.88|        Reject|              No|     Farah|                12680|
|    PR0089205|     2026-01-01|    PL01|     MC002|     OP0344|  Night|     PMP-210|         Pumps|          277|           278|             13|              50|      92.2|        57.79|          4.68|          Pass|              No|    Bharat|                12680|
|    PR0097214|     2026-01-01|    PL01|     MC002|     OP0114|Morning|     VLV-220|        Valves|          582|           516|             11|              48|    177.28|        57.77|          3.06|          Pass|              No|    Harini|                12680|
|    PR0101444|     2026-01-01|    PL01|     MC002|     OP0052|  Night|     VLV-320|        Valves|          607|           616|              0|            NULL|    241.09|        69.46|          4.09|        Reject|              No|     Irfan|                12680|
|    PR0013139|     2026-01-02|    PL01|     MC002|     OP0403|  Night|     MTR-200|        Motors|         1177|          1206|             52|              42|    293.34|        67.44|          4.71|        Rework|              No|     Farah|                22572|
|    PR0017970|     2026-01-02|    PL01|     MC002|     OP0469|Morning|     VLV-220|        Valves|          795|           663|             13|              28|    236.89|        46.17|          2.81|          Pass|              No|     Farah|                22572|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------+
only showing top 20 rows

10. Display previous production output using lag().

In [ ]:
df2 = df.withColumn("previous_output", F.lag("units_produced").over(Window.partitionBy("machine_id").orderBy("production_date")))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|previous_output|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
|    PR0001004|     2026-01-01|    PL01|     MC002|     OP0424|  Night|     VLV-120|        Valves|          517|           520|             14|               0|    133.77|        52.65|          4.53|          Pass|              No|    Harini|           NULL|
|    PR0003457|     2026-01-01|    PL01|     MC002|     OP0300|  Night|     CTL-330|   Controllers|          757|           660|             34|              38|    160.47|        58.86|          2.55|        Rework|              No|    Harini|            520|
|    PR0004579|     2026-01-01|    PL01|     MC002|     OP0648|Morning|     PMP-110|         Pumps|          382|           362|             13|               4|     67.29|         70.7|          4.44|          Pass|              No|     Gopal|            660|
|    PR0007449|     2026-01-01|    PL01|     MC002|     OP0435|Evening|     CTL-130|   Controllers|          433|           420|              6|              11|    161.43|        59.12|          3.14|          Pass|              No|    Harini|            362|
|    PR0014425|     2026-01-01|    PL01|     MC002|     OP0041|Morning|     MTR-200|        Motors|          737|           710|              4|              12|    338.49|        71.22|          2.29|          Pass|              No|    Harini|            420|
|    PR0017340|     2026-01-01|    PL01|     MC002|     OP0556|Evening|     VLV-320|        Valves|          988|           829|             22|              55|    309.43|        67.98|          4.63|          Pass|              No|     Farah|            710|
|    PR0021804|     2026-01-01|    PL01|     MC002|     OP0220|Morning|     CTL-130|   Controllers|         1099|          1064|             31|              41|    441.84|        70.18|          3.49|          Pass|              No|     Anita|            829|
|    PR0039968|     2026-01-01|    PL01|     MC002|     OP0309|  Night|     VLV-120|        Valves|         1127|          1159|             41|              45|    320.98|        72.94|           4.3|          Pass|              No|     Irfan|           1064|
|    PR0051741|     2026-01-01|    PL01|     MC002|     OP0549|Morning|     CTL-330|   Controllers|          311|           261|              6|              22|     61.65|        53.85|          3.03|        Reject|              No|    Charan|           1159|
|    PR0062464|     2026-01-01|    PL01|     MC002|     OP0199|  Night|     PMP-110|         Pumps|          920|           853|             14|              46|    367.01|         NULL|          3.89|        Reject|              No|    Harini|            261|
|    PR0063055|     2026-01-01|    PL01|     MC002|     OP0218|Evening|     PMP-310|         Pumps|         1124|          1022|              2|               0|    377.08|        68.29|          4.82|          Pass|              No|     Gopal|            853|
|    PR0064058|     2026-01-01|    PL01|     MC002|     OP0166|Morning|     VLV-320|        Valves|          602|           606|              0|              49|     310.0|        59.54|           0.8|          Pass|              No|     Farah|           1022|
|    PR0074326|     2026-01-01|    PL01|     MC002|     OP0271|  Night|     VLV-220|        Valves|         1141|          1106|             35|             121|     440.6|        63.09|          0.91|          Pass|             Yes|    Bharat|            606|
|    PR0081104|     2026-01-01|    PL01|     MC002|     OP0490|Evening|     MTR-200|        Motors|          877|           769|             30|              72|    267.64|        66.52|          3.07|          Pass|              No|     Gopal|           1106|
|    PR0084720|     2026-01-01|    PL01|     MC002|     OP0132|  Night|     PMP-110|         Pumps|         1102|           929|             34|               0|    367.07|        57.04|          1.88|        Reject|              No|     Farah|            769|
|    PR0089205|     2026-01-01|    PL01|     MC002|     OP0344|  Night|     PMP-210|         Pumps|          277|           278|             13|              50|      92.2|        57.79|          4.68|          Pass|              No|    Bharat|            929|
|    PR0097214|     2026-01-01|    PL01|     MC002|     OP0114|Morning|     VLV-220|        Valves|          582|           516|             11|              48|    177.28|        57.77|          3.06|          Pass|              No|    Harini|            278|
|    PR0101444|     2026-01-01|    PL01|     MC002|     OP0052|  Night|     VLV-320|        Valves|          607|           616|              0|            NULL|    241.09|        69.46|          4.09|        Reject|              No|     Irfan|            516|
|    PR0013139|     2026-01-02|    PL01|     MC002|     OP0403|  Night|     MTR-200|        Motors|         1177|          1206|             52|              42|    293.34|        67.44|          4.71|        Rework|              No|     Farah|            616|
|    PR0017970|     2026-01-02|    PL01|     MC002|     OP0469|Morning|     VLV-220|        Valves|          795|           663|             13|              28|    236.89|        46.17|          2.81|          Pass|              No|     Farah|           1206|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+
only showing top 20 rows

11. Display next production output using lead().

In [ ]:
df2 = df.withColumn("next_output", F.lead("units_produced").over(Window.partitionBy("machine_id").orderBy("production_date")))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|next_output|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
|    PR0001004|     2026-01-01|    PL01|     MC002|     OP0424|  Night|     VLV-120|        Valves|          517|           520|             14|               0|    133.77|        52.65|          4.53|          Pass|              No|    Harini|        660|
|    PR0003457|     2026-01-01|    PL01|     MC002|     OP0300|  Night|     CTL-330|   Controllers|          757|           660|             34|              38|    160.47|        58.86|          2.55|        Rework|              No|    Harini|        362|
|    PR0004579|     2026-01-01|    PL01|     MC002|     OP0648|Morning|     PMP-110|         Pumps|          382|           362|             13|               4|     67.29|         70.7|          4.44|          Pass|              No|     Gopal|        420|
|    PR0007449|     2026-01-01|    PL01|     MC002|     OP0435|Evening|     CTL-130|   Controllers|          433|           420|              6|              11|    161.43|        59.12|          3.14|          Pass|              No|    Harini|        710|
|    PR0014425|     2026-01-01|    PL01|     MC002|     OP0041|Morning|     MTR-200|        Motors|          737|           710|              4|              12|    338.49|        71.22|          2.29|          Pass|              No|    Harini|        829|
|    PR0017340|     2026-01-01|    PL01|     MC002|     OP0556|Evening|     VLV-320|        Valves|          988|           829|             22|              55|    309.43|        67.98|          4.63|          Pass|              No|     Farah|       1064|
|    PR0021804|     2026-01-01|    PL01|     MC002|     OP0220|Morning|     CTL-130|   Controllers|         1099|          1064|             31|              41|    441.84|        70.18|          3.49|          Pass|              No|     Anita|       1159|
|    PR0039968|     2026-01-01|    PL01|     MC002|     OP0309|  Night|     VLV-120|        Valves|         1127|          1159|             41|              45|    320.98|        72.94|           4.3|          Pass|              No|     Irfan|        261|
|    PR0051741|     2026-01-01|    PL01|     MC002|     OP0549|Morning|     CTL-330|   Controllers|          311|           261|              6|              22|     61.65|        53.85|          3.03|        Reject|              No|    Charan|        853|
|    PR0062464|     2026-01-01|    PL01|     MC002|     OP0199|  Night|     PMP-110|         Pumps|          920|           853|             14|              46|    367.01|         NULL|          3.89|        Reject|              No|    Harini|       1022|
|    PR0063055|     2026-01-01|    PL01|     MC002|     OP0218|Evening|     PMP-310|         Pumps|         1124|          1022|              2|               0|    377.08|        68.29|          4.82|          Pass|              No|     Gopal|        606|
|    PR0064058|     2026-01-01|    PL01|     MC002|     OP0166|Morning|     VLV-320|        Valves|          602|           606|              0|              49|     310.0|        59.54|           0.8|          Pass|              No|     Farah|       1106|
|    PR0074326|     2026-01-01|    PL01|     MC002|     OP0271|  Night|     VLV-220|        Valves|         1141|          1106|             35|             121|     440.6|        63.09|          0.91|          Pass|             Yes|    Bharat|        769|
|    PR0081104|     2026-01-01|    PL01|     MC002|     OP0490|Evening|     MTR-200|        Motors|          877|           769|             30|              72|    267.64|        66.52|          3.07|          Pass|              No|     Gopal|        929|
|    PR0084720|     2026-01-01|    PL01|     MC002|     OP0132|  Night|     PMP-110|         Pumps|         1102|           929|             34|               0|    367.07|        57.04|          1.88|        Reject|              No|     Farah|        278|
|    PR0089205|     2026-01-01|    PL01|     MC002|     OP0344|  Night|     PMP-210|         Pumps|          277|           278|             13|              50|      92.2|        57.79|          4.68|          Pass|              No|    Bharat|        516|
|    PR0097214|     2026-01-01|    PL01|     MC002|     OP0114|Morning|     VLV-220|        Valves|          582|           516|             11|              48|    177.28|        57.77|          3.06|          Pass|              No|    Harini|        616|
|    PR0101444|     2026-01-01|    PL01|     MC002|     OP0052|  Night|     VLV-320|        Valves|          607|           616|              0|            NULL|    241.09|        69.46|          4.09|        Reject|              No|     Irfan|       1206|
|    PR0013139|     2026-01-02|    PL01|     MC002|     OP0403|  Night|     MTR-200|        Motors|         1177|          1206|             52|              42|    293.34|        67.44|          4.71|        Rework|              No|     Farah|        663|
|    PR0017970|     2026-01-02|    PL01|     MC002|     OP0469|Morning|     VLV-220|        Valves|          795|           663|             13|              28|    236.89|        46.17|          2.81|          Pass|              No|     Farah|        241|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------+
only showing top 20 rows

12. Calculate change from the previous production run.

In [ ]:
df2 = df.withColumn("change_from_previous_output", F.col("units_produced") - F.lag("units_produced").over(Window.partitionBy("machine_id").orderBy("production_date")))
df2.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|change_from_previous_output|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------------+
|    PR0001004|     2026-01-01|    PL01|     MC002|     OP0424|  Night|     VLV-120|        Valves|          517|           520|             14|               0|    133.77|        52.65|          4.53|          Pass|              No|    Harini|                       NULL|
|    PR0003457|     2026-01-01|    PL01|     MC002|     OP0300|  Night|     CTL-330|   Controllers|          757|           660|             34|              38|    160.47|        58.86|          2.55|        Rework|              No|    Harini|                        140|
|    PR0004579|     2026-01-01|    PL01|     MC002|     OP0648|Morning|     PMP-110|         Pumps|          382|           362|             13|               4|     67.29|         70.7|          4.44|          Pass|              No|     Gopal|                       -298|
|    PR0007449|     2026-01-01|    PL01|     MC002|     OP0435|Evening|     CTL-130|   Controllers|          433|           420|              6|              11|    161.43|        59.12|          3.14|          Pass|              No|    Harini|                         58|
|    PR0014425|     2026-01-01|    PL01|     MC002|     OP0041|Morning|     MTR-200|        Motors|          737|           710|              4|              12|    338.49|        71.22|          2.29|          Pass|              No|    Harini|                        290|
|    PR0017340|     2026-01-01|    PL01|     MC002|     OP0556|Evening|     VLV-320|        Valves|          988|           829|             22|              55|    309.43|        67.98|          4.63|          Pass|              No|     Farah|                        119|
|    PR0021804|     2026-01-01|    PL01|     MC002|     OP0220|Morning|     CTL-130|   Controllers|         1099|          1064|             31|              41|    441.84|        70.18|          3.49|          Pass|              No|     Anita|                        235|
|    PR0039968|     2026-01-01|    PL01|     MC002|     OP0309|  Night|     VLV-120|        Valves|         1127|          1159|             41|              45|    320.98|        72.94|           4.3|          Pass|              No|     Irfan|                         95|
|    PR0051741|     2026-01-01|    PL01|     MC002|     OP0549|Morning|     CTL-330|   Controllers|          311|           261|              6|              22|     61.65|        53.85|          3.03|        Reject|              No|    Charan|                       -898|
|    PR0062464|     2026-01-01|    PL01|     MC002|     OP0199|  Night|     PMP-110|         Pumps|          920|           853|             14|              46|    367.01|         NULL|          3.89|        Reject|              No|    Harini|                        592|
|    PR0063055|     2026-01-01|    PL01|     MC002|     OP0218|Evening|     PMP-310|         Pumps|         1124|          1022|              2|               0|    377.08|        68.29|          4.82|          Pass|              No|     Gopal|                        169|
|    PR0064058|     2026-01-01|    PL01|     MC002|     OP0166|Morning|     VLV-320|        Valves|          602|           606|              0|              49|     310.0|        59.54|           0.8|          Pass|              No|     Farah|                       -416|
|    PR0074326|     2026-01-01|    PL01|     MC002|     OP0271|  Night|     VLV-220|        Valves|         1141|          1106|             35|             121|     440.6|        63.09|          0.91|          Pass|             Yes|    Bharat|                        500|
|    PR0081104|     2026-01-01|    PL01|     MC002|     OP0490|Evening|     MTR-200|        Motors|          877|           769|             30|              72|    267.64|        66.52|          3.07|          Pass|              No|     Gopal|                       -337|
|    PR0084720|     2026-01-01|    PL01|     MC002|     OP0132|  Night|     PMP-110|         Pumps|         1102|           929|             34|               0|    367.07|        57.04|          1.88|        Reject|              No|     Farah|                        160|
|    PR0089205|     2026-01-01|    PL01|     MC002|     OP0344|  Night|     PMP-210|         Pumps|          277|           278|             13|              50|      92.2|        57.79|          4.68|          Pass|              No|    Bharat|                       -651|
|    PR0097214|     2026-01-01|    PL01|     MC002|     OP0114|Morning|     VLV-220|        Valves|          582|           516|             11|              48|    177.28|        57.77|          3.06|          Pass|              No|    Harini|                        238|
|    PR0101444|     2026-01-01|    PL01|     MC002|     OP0052|  Night|     VLV-320|        Valves|          607|           616|              0|            NULL|    241.09|        69.46|          4.09|        Reject|              No|     Irfan|                        100|
|    PR0013139|     2026-01-02|    PL01|     MC002|     OP0403|  Night|     MTR-200|        Motors|         1177|          1206|             52|              42|    293.34|        67.44|          4.71|        Rework|              No|     Farah|                        590|
|    PR0017970|     2026-01-02|    PL01|     MC002|     OP0469|Morning|     VLV-220|        Valves|          795|           663|             13|              28|    236.89|        46.17|          2.81|          Pass|              No|     Farah|                       -543|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------------------+
only showing top 20 rows

13. Rank product families by total output.

In [ ]:
df2 = df.groupBy("product_family").agg(F.sum("units_produced").alias("total_output"))
df2 = df2.withColumn("rank", F.rank().over(Window.orderBy(F.desc("total_output"))))
df2.show()

+--------------+------------+----+
|product_family|total_output|rank|
+--------------+------------+----+
|        Valves|    20433082|   1|
|         Pumps|    20208739|   2|
|   Controllers|    20168572|   3|
|        Motors|    20117495|   4|
+--------------+------------+----+

**18. Date and Time Functions**

In [ ]:
from pyspark.sql.functions import to_date, year, month, day

Using production_date:

1. Convert to DateType.
2. Extract year.
3. Extract month.
4. Extract day.
5. Extract month name.
6. Extract day name.
7. Create year_month .
8. Calculate monthly production.
9. Calculate monthly defects.
10. Calculate production by month and plant.
15. Find the month with the highest total output.

In [ ]:
# Base DataFrame with date parts (never overwrite this one)
df_dates = (df
    .withColumn("production_date", F.to_date("production_date")) #1
    .withColumn("year", F.year("production_date")) #2
    .withColumn("month", F.month("production_date")) #3
    .withColumn("day", F.dayofmonth("production_date")) #4
    .withColumn("month_name", F.date_format("production_date", "MMMM")) #5
    .withColumn("day_name", F.date_format("production_date", "EEEE")) #6
    .withColumn("year_month", F.date_format("production_date", "yyyy-MM"))) #7

# 8. Monthly production
monthly_prod = (df_dates.groupBy("year_month")
    .agg(F.sum("units_produced").alias("monthly_production"))
    .orderBy("year_month"))
monthly_prod.show()

# 9. Monthly defects
monthly_def = (df_dates.groupBy("year_month")
    .agg(F.sum("defective_units").alias("monthly_defects"))
    .orderBy("year_month"))
monthly_def.show()

# 10. Production by month and plant
(df_dates.groupBy("year_month", "plant_id")
    .agg(F.sum("units_produced").alias("total_production"))
    .orderBy("year_month", "plant_id").show())

# 15. Month with the highest total output
monthly_prod.orderBy(F.desc("monthly_production")).limit(1).show()

+----------+------------------+
|year_month|monthly_production|
+----------+------------------+
|   2026-01|           8478059|
|   2026-02|           7810891|
|   2026-03|           8441121|
|   2026-04|           8211005|
|   2026-05|           8507542|
|   2026-06|           8400505|
|   2026-07|           8476416|
|   2026-08|           8529150|
|   2026-09|           8115221|
|   2026-10|           5957978|
+----------+------------------+

+----------+---------------+
|year_month|monthly_defects|
+----------+---------------+
|   2026-01|         211741|
|   2026-02|         197462|
|   2026-03|         212036|
|   2026-04|         208707|
|   2026-05|         212049|
|   2026-06|         210381|
|   2026-07|         210482|
|   2026-08|         214807|
|   2026-09|         202990|
|   2026-10|         149589|
+----------+---------------+

+----------+--------+----------------+
|year_month|plant_id|total_production|
+----------+--------+----------------+
|   2026-01|    PL01|         1451436|
|   2026-01|    PL02|         1419252|
|   2026-01|    PL03|         1429811|
|   2026-01|    PL04|         1399488|
|   2026-01|    PL05|         1375887|
|   2026-01|    PL06|         1402185|
|   2026-02|    PL01|         1342273|
|   2026-02|    PL02|         1278581|
|   2026-02|    PL03|         1305531|
|   2026-02|    PL04|         1292557|
|   2026-02|    PL05|         1324271|
|   2026-02|    PL06|         1267678|
|   2026-03|    PL01|         1442140|
|   2026-03|    PL02|         1359740|
|   2026-03|    PL03|         1416484|
|   2026-03|    PL04|         1447603|
|   2026-03|    PL05|         1411435|
|   2026-03|    PL06|         1363719|
|   2026-04|    PL01|         1350450|
|   2026-04|    PL02|         1369684|
+----------+--------+----------------+
only showing top 20 rows
+----------+------------------+
|year_month|monthly_production|
+----------+------------------+
|   2026-08|           8529150|
+----------+------------------+

11. Find production between two dates.

In [ ]:
df_dt = df_dates.filter(
    (df_dates["production_date"] >= "2023-01-01") &
    (df_dates["production_date"] <= "2023-12-31")
)
df_dt.show()

+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+--------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name|day_name|year_month|
+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+--------+----------+
+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+--------+----------+

12. Add 7 days to production date.

In [ ]:
df_dt = df_dates.withColumn("plus_7_date", F.date_add("production_date", 7))
df_dt.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+-----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|plus_7_date|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+-----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|2026|    8|  7|    August|   Friday|   2026-08| 2026-08-14|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|2026|    8|  3|    August|   Monday|   2026-08| 2026-08-10|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|2026|    5| 20|       May|Wednesday|   2026-05| 2026-05-27|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|2026|    1| 15|   January| Thursday|   2026-01| 2026-01-22|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|2026|    9| 21| September|   Monday|   2026-09| 2026-09-28|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|2026|    9|  3| September| Thursday|   2026-09| 2026-09-10|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|2026|    5|  7|       May| Thursday|   2026-05| 2026-05-14|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|2026|    8| 17|    August|   Monday|   2026-08| 2026-08-24|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|2026|    3| 10|     March|  Tuesday|   2026-03| 2026-03-17|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|2026|    2| 13|  February|   Friday|   2026-02| 2026-02-20|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|2026|    9| 29| September|  Tuesday|   2026-09| 2026-10-06|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|2026|    7| 10|      July|   Friday|   2026-07| 2026-07-17|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|2026|    7| 19|      July|   Sunday|   2026-07| 2026-07-26|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|2026|    5|  5|       May|  Tuesday|   2026-05| 2026-05-12|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|2026|    3| 15|     March|   Sunday|   2026-03| 2026-03-22|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|2026|    3|  3|     March|  Tuesday|   2026-03| 2026-03-10|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|2026|    8|  4|    August|  Tuesday|   2026-08| 2026-08-11|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|2026|    1| 30|   January|   Friday|   2026-01| 2026-02-06|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|2026|    1| 11|   January|   Sunday|   2026-01| 2026-01-18|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|2026|    2| 18|  February|Wednesday|   2026-02| 2026-02-25|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+-----------+
only showing top 20 rows

13. Subtract 30 days.

In [ ]:
df_dt = df_dates.withColumn("minus_30_days", F.date_sub("production_date", 30))
df_dt.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+-------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|minus_30_days|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+-------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|2026|    8|  7|    August|   Friday|   2026-08|   2026-07-08|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|2026|    8|  3|    August|   Monday|   2026-08|   2026-07-04|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|2026|    5| 20|       May|Wednesday|   2026-05|   2026-04-20|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|2026|    1| 15|   January| Thursday|   2026-01|   2025-12-16|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|2026|    9| 21| September|   Monday|   2026-09|   2026-08-22|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|2026|    9|  3| September| Thursday|   2026-09|   2026-08-04|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|2026|    5|  7|       May| Thursday|   2026-05|   2026-04-07|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|2026|    8| 17|    August|   Monday|   2026-08|   2026-07-18|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|2026|    3| 10|     March|  Tuesday|   2026-03|   2026-02-08|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|2026|    2| 13|  February|   Friday|   2026-02|   2026-01-14|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|2026|    9| 29| September|  Tuesday|   2026-09|   2026-08-30|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|2026|    7| 10|      July|   Friday|   2026-07|   2026-06-10|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|2026|    7| 19|      July|   Sunday|   2026-07|   2026-06-19|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|2026|    5|  5|       May|  Tuesday|   2026-05|   2026-04-05|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|2026|    3| 15|     March|   Sunday|   2026-03|   2026-02-13|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|2026|    3|  3|     March|  Tuesday|   2026-03|   2026-02-01|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|2026|    8|  4|    August|  Tuesday|   2026-08|   2026-07-05|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|2026|    1| 30|   January|   Friday|   2026-01|   2025-12-31|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|2026|    1| 11|   January|   Sunday|   2026-01|   2025-12-12|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|2026|    2| 18|  February|Wednesday|   2026-02|   2026-01-19|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+-------------+
only showing top 20 rows

14. Calculate difference from current date.

In [ ]:
df_dt = df_dates.withColumn("days_from_today", F.datediff(F.current_date(), "production_date"))
df_dt.show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+---------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|days_from_today|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+---------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|2026|    8|  7|    August|   Friday|   2026-08|             77|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|2026|    8|  3|    August|   Monday|   2026-08|             81|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|2026|    5| 20|       May|Wednesday|   2026-05|            156|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|2026|    1| 15|   January| Thursday|   2026-01|            281|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|2026|    9| 21| September|   Monday|   2026-09|             32|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|2026|    9|  3| September| Thursday|   2026-09|             50|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|2026|    5|  7|       May| Thursday|   2026-05|            169|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|2026|    8| 17|    August|   Monday|   2026-08|             67|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|2026|    3| 10|     March|  Tuesday|   2026-03|            227|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|2026|    2| 13|  February|   Friday|   2026-02|            252|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|2026|    9| 29| September|  Tuesday|   2026-09|             24|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|2026|    7| 10|      July|   Friday|   2026-07|            105|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|2026|    7| 19|      July|   Sunday|   2026-07|             96|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|2026|    5|  5|       May|  Tuesday|   2026-05|            171|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|2026|    3| 15|     March|   Sunday|   2026-03|            222|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|2026|    3|  3|     March|  Tuesday|   2026-03|            234|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|2026|    8|  4|    August|  Tuesday|   2026-08|             80|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|2026|    1| 30|   January|   Friday|   2026-01|            266|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|2026|    1| 11|   January|   Sunday|   2026-01|            285|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|2026|    2| 18|  February|Wednesday|   2026-02|            247|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+---------------+
only showing top 20 rows